{-# LANGUAGE OverloadedStrings #-}

module OligoDesigner.SpecScorer where

import           Bio.Tools.Sequence.OligoDesigner.Scorer (rnaScore, rnaMatrixScore, gcContent,
                                                            oligsGCContentDifference, gcContentScoreBySequence, commonScore, gcContentScoreByOligs)
import           Bio.Tools.Sequence.OligoDesigner.Types  (Olig (..),
                                                          OligLight (..),
                                                          OligSet (..),
                                                          OligSplitting (..), MatrixCell(..),
                                                          OligsDesignerConfig(..), OligsSplittingConfig(..), standardTemperature)
import           Test.Hspec                              (Spec, describe, it,
                                                          shouldBe)
import Data.Matrix (matrix)
import Bio.Tools.Sequence.OligoDesigner.Utils (assemble, buildOligSet)
import Bio.Tools.Sequence.OligoDesigner.Printer (printResult)
import Debug.Trace (trace)
import Data.Text (toUpper)
import Data.Default (def)
import Bio.Tools.Sequence.CodonOptimization (CodonOptimizationConfig(..))
import Bio.Tools.Sequence.CodonOptimization.Types (Organism(..), defaultForbiddenRegexp)
import Bio.NucleicAcid.Nucleotide (DNA(..))
import Bio.Tools.Sequence.ViennaRNA.Cofold (cofold)
import Bio.Tools.Sequence.ViennaRNA.Fold (fold)
import Bio.Tools.Sequence.OligoDesigner.Prettifier (prettyDNA, prettyMatrixCell)
import Text.Regex.TDFA (Regex, makeRegex)
import Bio.Tools.Sequence.CodonOptimization.Algo (scoreByWindow)
import Bio.Tools.Sequence.OligoDesigner.RNAMatrixBuilder (rnaMatrix)

oligoDesignerScoreSpec :: Spec
oligoDesignerScoreSpec = describe "Oligo-Designer score spec" $ do
    scoreRNAFoldingSpec
    scoreRNAFoldingSpec2

    rnaMatrixScoreSpec

    gcContentSpec
    gcContentDifferenceSpec
    gcContentDifferenceForTheSameOligsSpec
    gcContentDifferenceForEmptyOligsSpec

    dnaGCContentScoreSpec
    commonScoreSpec
--       tttt

scoreRNAFoldingSpec :: Spec
scoreRNAFoldingSpec =
    describe "scoreRNAFoldingSpec" $
    it "should correct score oligs" $ do
        let coords = OligSplitting [(0, 60), (60, 120)] [(30, 90), (90, 150)]
        let oligs =
                OligSet
                    [ Olig "GCTAGCACCAAGGGCCCCAGCGTGTTTCCTCTGGCCCCTAGCAGCAAGAGCACCAGCGGC" 0 60
                    , Olig "GGCACCGCCGCCCTGGGCTGCCTGGTGAAGGACTACTTCCCTGAGCCTGTGACCGTGAGC" 60 120
                    ]
                    [ Olig "CTTCACCAGGCAGCCCAGGGCGGCGGTGCCGCCGCTGGTGCTCTTGCTGCTAGGGGCCAG" 30 90
                    , Olig "CACGCCGCTGGTCAGGGCGCCGCTGTTCCAGCTCACGGTCACAGGCTCAGGGAAGTAGTC" 90 150
                    ]
                    coords
        rnaScore oligs `shouldBe` 13.699997

scoreRNAFoldingSpec2 :: Spec
scoreRNAFoldingSpec2 =
    describe "scoreRNAFoldingSpec2" $
    it "should correct score oligs" $ do
         let coords = OligSplitting [(0, 60), (60, 120), (120, 180), (180, 240), (240, 300), (300, 360)]
                                    [(30, 90), (90, 150), (150, 210), (210, 270), (270, 330), (330, 390)]
         let oligs =
                 OligSet
                     [ Olig "GCTAGCACCAAGGGCCCCAGCGTGTTTCCTCTGGCCCCTAGCAGCAAGAGCACCAGCGGC" 0 60
                     , Olig "GGCACCGCCGCCCTGGGCTGCCTGGTGAAGGACTACTTCCCTGAGCCTGTGACCGTGAGC" 60 120
                     , Olig "TGGAACAGCGGCGCCCTGACCAGCGGCGTGCACACCTTCCCTGCCGTGCTGCAGAGCAGC" 120 180
                     , Olig "GGCCTGTACAGCCTGAGCAGCGTGGTGACCGTGCCTAGCAGCAGCCTGGGCACCCAGACC" 180 240
                     , Olig "TACATCTGCAACGTGAACCACAAGCCTAGCAACACCAAGGTGGACAAGAAGGTGGAGCCC" 240 300
                     , Olig "AAGAGCTGCGACCGTACGCACACCTGCCCCCCCTGCCCCGCCCCCGAGCTGCTGGGCGGC" 300 360
                     ]
                     [ Olig "CTTCACCAGGCAGCCCAGGGCGGCGGTGCCGCCGCTGGTGCTCTTGCTGCTAGGGGCCAG" 30 90
                     , Olig "CACGCCGCTGGTCAGGGCGCCGCTGTTCCAGCTCACGGTCACAGGCTCAGGGAAGTAGTC" 90 150
                     , Olig "GGTCACCACGCTGCTCAGGCTGTACAGGCCGCTGCTCTGCAGCACGGCAGGGAAGGTGTG" 150 210
                     , Olig "GCTAGGCTTGTGGTTCACGTTGCAGATGTAGGTCTGGGTGCCCAGGCTGCTGCTAGGCAC" 210 270
                     , Olig "GGGGCAGGTGTGCGTACGGTCGCAGCTCTTGGGCTCCACCTTCTTGTCCACCTTGGTGTT" 270 330
                     , Olig "AGGCTTAGGAGGGAACAGGAACACGCTAGGGCCGCCCAGCAGCTCGGGGGCGGGGCAGGG" 330 390
                     ]
                     coords
         rnaScore oligs `shouldBe` 1.1000061

rnaMatrixScoreSpec :: Spec
rnaMatrixScoreSpec =
    describe "rnaMatrixScoreSpec" $
    it "" $ do
        let mtx = matrix 4 4 generatorRealMatrix
        let res = rnaMatrixScore mtx
        res `shouldBe` 13.699997
    where
      generatorRealMatrix :: (Int, Int) -> MatrixCell
      generatorRealMatrix (1, 1) = MatrixCell (OligLight "GCTAGCACCAAGGGCCCCAGCGTGTTTCCTCTGGCCCCTAGCAGCAAGAGCACCAGCGGC" (Olig "GCTAGCACCAAGGGCCCCAGCGTGTTTCCTCTGGCCCCTAGCAGCAAGAGCACCAGCGGC" 0 60))
                                              (OligLight "GCTAGCACCAAGGGCCCCAGCGTGTTTCCTCTGGCCCCTAGCAGCAAGAGCACCAGCGGC" (Olig "GCTAGCACCAAGGGCCCCAGCGTGTTTCCTCTGGCCCCTAGCAGCAAGAGCACCAGCGGC" 0 60)) (-36.9)
      generatorRealMatrix (1, 2) = MatrixCell (OligLight "GCTAGCACCAAGGGCCCCAGCGTGTTTCCTCTGGCCCCTAGCAGCAAGAGCACCAGCGGC" (Olig "GCTAGCACCAAGGGCCCCAGCGTGTTTCCTCTGGCCCCTAGCAGCAAGAGCACCAGCGGC" 0 60))
                                              (OligLight "CTTCACCAGGCAGCCCAGGGCGGCGGTGCCGCCGCTGGTGCTCTTGCTGCTAGGGGCCAG" (Olig "CTTCACCAGGCAGCCCAGGGCGGCGGTGCCGCCGCTGGTGCTCTTGCTGCTAGGGGCCAG" 30 90)) (-84.9)
      generatorRealMatrix (1, 3) = MatrixCell (OligLight "GCTAGCACCAAGGGCCCCAGCGTGTTTCCTCTGGCCCCTAGCAGCAAGAGCACCAGCGGC" (Olig "GCTAGCACCAAGGGCCCCAGCGTGTTTCCTCTGGCCCCTAGCAGCAAGAGCACCAGCGGC" 0 60))
                                              (OligLight "GGCACCGCCGCCCTGGGCTGCCTGGTGAAGGACTACTTCCCTGAGCCTGTGACCGTGAGC" (Olig "GGCACCGCCGCCCTGGGCTGCCTGGTGAAGGACTACTTCCCTGAGCCTGTGACCGTGAGC" 60 120)) (-41.8)
      generatorRealMatrix (1, 4) = MatrixCell (OligLight "GCTAGCACCAAGGGCCCCAGCGTGTTTCCTCTGGCCCCTAGCAGCAAGAGCACCAGCGGC" (Olig "GCTAGCACCAAGGGCCCCAGCGTGTTTCCTCTGGCCCCTAGCAGCAAGAGCACCAGCGGC" 0 60))
                                              (OligLight "CACGCCGCTGGTCAGGGCGCCGCTGTTCCAGCTCACGGTCACAGGCTCAGGGAAGTAGTC" (Olig "CACGCCGCTGGTCAGGGCGCCGCTGTTCCAGCTCACGGTCACAGGCTCAGGGAAGTAGTC" 90 150)) (-48.5)
      generatorRealMatrix (2, 2) = MatrixCell (OligLight "CTTCACCAGGCAGCCCAGGGCGGCGGTGCCGCCGCTGGTGCTCTTGCTGCTAGGGGCCAG" (Olig "CTTCACCAGGCAGCCCAGGGCGGCGGTGCCGCCGCTGGTGCTCTTGCTGCTAGGGGCCAG" 30 90))
                                              (OligLight "CTTCACCAGGCAGCCCAGGGCGGCGGTGCCGCCGCTGGTGCTCTTGCTGCTAGGGGCCAG" (Olig "CTTCACCAGGCAGCCCAGGGCGGCGGTGCCGCCGCTGGTGCTCTTGCTGCTAGGGGCCAG" 30 90)) (-68)
      generatorRealMatrix (2, 3) = MatrixCell (OligLight "CTTCACCAGGCAGCCCAGGGCGGCGGTGCCGCCGCTGGTGCTCTTGCTGCTAGGGGCCAG" (Olig "CTTCACCAGGCAGCCCAGGGCGGCGGTGCCGCCGCTGGTGCTCTTGCTGCTAGGGGCCAG" 30 90))
                                              (OligLight "GGCACCGCCGCCCTGGGCTGCCTGGTGAAGGACTACTTCCCTGAGCCTGTGACCGTGAGC" (Olig "GGCACCGCCGCCCTGGGCTGCCTGGTGAAGGACTACTTCCCTGAGCCTGTGACCGTGAGC" 60 120)) (-92.2)
      generatorRealMatrix (2, 4) = MatrixCell (OligLight "CTTCACCAGGCAGCCCAGGGCGGCGGTGCCGCCGCTGGTGCTCTTGCTGCTAGGGGCCAG" (Olig "CTTCACCAGGCAGCCCAGGGCGGCGGTGCCGCCGCTGGTGCTCTTGCTGCTAGGGGCCAG" 30 90))
                                              (OligLight "CACGCCGCTGGTCAGGGCGCCGCTGTTCCAGCTCACGGTCACAGGCTCAGGGAAGTAGTC" (Olig "CACGCCGCTGGTCAGGGCGCCGCTGTTCCAGCTCACGGTCACAGGCTCAGGGAAGTAGTC" 90 150)) (-56.4)
      generatorRealMatrix (3, 3) = MatrixCell (OligLight "GGCACCGCCGCCCTGGGCTGCCTGGTGAAGGACTACTTCCCTGAGCCTGTGACCGTGAGC" (Olig "GGCACCGCCGCCCTGGGCTGCCTGGTGAAGGACTACTTCCCTGAGCCTGTGACCGTGAGC" 60 120))
                                              (OligLight "GGCACCGCCGCCCTGGGCTGCCTGGTGAAGGACTACTTCCCTGAGCCTGTGACCGTGAGC" (Olig "GGCACCGCCGCCCTGGGCTGCCTGGTGAAGGACTACTTCCCTGAGCCTGTGACCGTGAGC" 60 120)) (-45.7)
      generatorRealMatrix (3, 4) = MatrixCell (OligLight "GGCACCGCCGCCCTGGGCTGCCTGGTGAAGGACTACTTCCCTGAGCCTGTGACCGTGAGC" (Olig "GGCACCGCCGCCCTGGGCTGCCTGGTGAAGGACTACTTCCCTGAGCCTGTGACCGTGAGC" 60 120))
                                              (OligLight "CACGCCGCTGGTCAGGGCGCCGCTGTTCCAGCTCACGGTCACAGGCTCAGGGAAGTAGTC" (Olig "CACGCCGCTGGTCAGGGCGCCGCTGTTCCAGCTCACGGTCACAGGCTCAGGGAAGTAGTC" 90 150)) (-81.7)
      generatorRealMatrix (4, 4) = MatrixCell (OligLight "CACGCCGCTGGTCAGGGCGCCGCTGTTCCAGCTCACGGTCACAGGCTCAGGGAAGTAGTC" (Olig "CACGCCGCTGGTCAGGGCGCCGCTGTTCCAGCTCACGGTCACAGGCTCAGGGAAGTAGTC" 90 150))
                                              (OligLight "CACGCCGCTGGTCAGGGCGCCGCTGTTCCAGCTCACGGTCACAGGCTCAGGGAAGTAGTC" (Olig "CACGCCGCTGGTCAGGGCGCCGCTGTTCCAGCTCACGGTCACAGGCTCAGGGAAGTAGTC" 90 150)) (-44.5)
      generatorRealMatrix (x, y) = MatrixCell (OligLight "" (Olig "" 0 0)) (OligLight "" (Olig "" 0 0)) 0

gcContentSpec :: Spec
gcContentSpec = describe "gcContentSpec" $ it "" $ do
    gcContent "GGGGGG" `shouldBe` 100
    gcContent "GGGCCC" `shouldBe` 100
    gcContent "AAAAAA" `shouldBe` 0
    gcContent "TTAAAA" `shouldBe` 0
    gcContent "GGGGCCCCAAAATTTT" `shouldBe` 50
    gcContent "GCTAGCACCAAGGGCCCCAGCGTGTTTCCTCTGGCCCCTAGCAGCAAGAGCACCAGCGGC" `shouldBe` 66.66666666666667

gcContentDifferenceSpec :: Spec
gcContentDifferenceSpec =
    describe "gcContentDifferenceSpec" $
    it "" $ do
        let oligs = OligSet
                        [Olig "TTGATCTTCC" 0 10, Olig "TTATAAGAAA" 10 20] -- 40% & 10%
                        [Olig "TATAAGGAAG" 5 15, Olig "TTGTTTTCT" 15 24]  -- 30% & 22%
                        (OligSplitting [(0, 10), (10, 20)] [(5, 15), (15, 24)])
        let res = oligsGCContentDifference oligs
        res `shouldBe` 30

gcContentDifferenceForTheSameOligsSpec :: Spec
gcContentDifferenceForTheSameOligsSpec =
    describe "gcContentDifferenceForTheSameOligsSpec" $
    it "" $ do
        let oligs = OligSet
                        [Olig "TTGATCTTCC" 0 10, Olig "AAGATGTTCG" 10 20] -- 40% & 10%
                        [Olig "TAGTTCAACC" 5 15, Olig "TTCAACTTGG" 15 24]  -- 30% & 22%
                        (OligSplitting [(0, 10), (10, 20)] [(5, 15), (15, 24)])
        let res = oligsGCContentDifference oligs
        res `shouldBe` 0

gcContentDifferenceForEmptyOligsSpec :: Spec
gcContentDifferenceForEmptyOligsSpec =
    describe "gcContentDifferenceForEmptyOligsSpec" $
    it "" $ do
        let oligs = OligSet [] [] (OligSplitting [(0, 10), (10, 20)] [(5, 15), (15, 24)])
        let res = oligsGCContentDifference oligs
        res `shouldBe` 0

dnaGCContentScoreSpec :: Spec
dnaGCContentScoreSpec =
    describe "dnaGCContentScore" $
    it "" $ do
        let sequ = "GAAGTGCAGCTGGTGGAGTCTGGGGGAGGCGTGGTACAGCCTGGCAGGTCCCTGTCTCCTGTGCAGCCTCTGGATTCACCTTTAA" ++
                        "CGATTATACCATGCACTGGGTCCAGCTCCAGGGAAGGGCCTGGAGTGGGTCTCAGGTATTAGTTGGAATGGCGGTAG"
        gcContentScoreBySequence "GACATACAAATGACTCAAAGTCCATCTACTCTATCCGCGAGTGTCGGCGACCGCGTAACTATTACGTGCAGGGCTTCACAAAGCATCGGTTCGGCTTTAGCATGGTATCAGCAGAAGCCTGGGAAAGCTCCTAAGTTACTGATCTATAAGGCAAGTGCCCTGGAGAACGGTGTTCCGTCTAGGTTTTCGGGCTCTGGTAGTGGGACCGAGTTCACACTGACAATAAGCAGTCTCCAACCCGATGATTTCGCCACCTACTACTGCCAGCACCTGACCTTCGGACAAGGGACGAGGTTGGAAATCAAA"
            43 `shouldBe` 0.8144094847241223
        gcContentScoreBySequence sequ 64 `shouldBe` 0.9066358024691358
        gcContentScoreBySequence "GGGGGGGGGG" 100 `shouldBe` 1
        gcContentScoreBySequence "AAAAAAAAAA" 100 `shouldBe` 0
        gcContentScoreBySequence "AAAAAGGGGG" 100 `shouldBe` 0.5
        gcContentScoreBySequence "AAAAAGGGGG" 50 `shouldBe` 1
        gcContentScoreBySequence "GGGGGGGGGGGGGGGGGGGG" 50 `shouldBe` 0
        gcContentScoreBySequence "G" 50 `shouldBe` 0
        gcContentScoreBySequence "AAAAAAAAAA" 50 `shouldBe` 0
        gcContentScoreBySequence "GCTAGCACCAAGGGCCCCAGCGTGTTTCCTCTGGCCCCTAGCAGCAAGAGCACCAGCGGCGGCACCGCCGCCCTGGG" 71 `shouldBe` 0.993963782696177

commonScoreSpec :: Spec
commonScoreSpec =
    describe "commonScoreSpec" $
    it "" $ do
        let oligs = OligSet
                        [Olig "TTGATCTTCC" 0 10, Olig "TTATAAGAAA" 10 20] -- 40% & 10%
                        [Olig "TATAAGGAAG" 5 15, Olig "TTGTTTTCT" 15 24]  -- 30% & 22%
                        (OligSplitting [(0, 10), (10, 20)] [(5, 15), (15, 24)])
        let codonConf = CodonOptimizationConfig CHO 3 1 1 0.5 1.4 40 0.001 2.6 100 1 43 defaultForbiddenRegexp
        commonScore (OligsDesignerConfig codonConf def 1 0 0 0 1) oligs `shouldBe` -0.06007751753163892

--tttt :: Spec
--tttt =
--    describe "tttt" $
--    it "" $ do
--        let codonConf = CodonOptimizationConfig CHO 3 1 1 0.5 1.4 40 0.001 2.6 100 1 51 defaultForbiddenRegexp
--        let conf = OligsDesignerConfig codonConf def 0.6 0.1 0.4 50 30
--        arr <- sequence [printResult conf "Y" (buildOligSet splitting dna) | (dna, splitting) <- oligs]
--        True `shouldBe` True
--
--
--oligs :: [([DNA], OligSplitting)]
--oligs = [( "CAGATAGTCTTATCGCAAAGTCCAGCCACATTAAGTGCATCGCCGGGAGAGCGGGTAACAATGACCTGCCGGGCATCGTCGAGTGTAAGCTACATCCATTGGTTTCAGCAAAAGCCGGGAAGTGCCCCGAAACCGTTAATCTACGCCACCTCTAATCTGGCAAGCGGCGTCCCGAGTAGATTCAGTGGAAGTGGATCGGGAACAGATTTTACACTGACCATATCTAGGCTGGAGCCGGAGGACTTTGCAACCTATTATTGCCAGCAGTGGACAAGCAACCCACCAACATTTGGCGGTGGAACAAAGGTCGAAATAAAA"
--       , OligSplitting
--             [(0,58), (58,116), (116,174), (174,232), (232,290)]
--             [(29,87), (87,145), (145,203), (203,261), (261,318)])
--     ,( "CAAATAGTCCTGTCGCAGAGTCCGGCAACCCTGTCAGCCAGTCCAGGAGAAAGGGTAACAATGACCTGTAGAGCCAGTTCGAGTGTCTCGTACATCCATTGGTTCCAACAAAAGCCGGGTTCGGCCCCAAAGCCGTTAATCTATGCCACATCAAACTTAGCCAGTGGAGTACCAAGTAGGTTCTCAGGAAGTGGGAGTGGGACTGACTTTACACTGACCATATCCAGACTGGAGCCGGAGGATTTCGCCACATATTACTGTCAGCAGTGGACAAGTAACCCACCAACCTTTGGAGGAGGGACCAAGGTAGAAATCAAG"
--             , OligSplitting
--                   [(0,58), (58,116), (116,174), (174,232), (232,290)]
--                   [(29,87), (87,145), (145,203), (203,261), (261,318)])
--     ,( "CAGATCGTCCTAAGTCAAAGTCCAGCAACACTGTCGGCCTCGCCGGGAGAACGGGTCACTATGACTTGTAGAGCAAGTTCGAGTGTAAGTTACATACATTGGTTTCAACAGAAGCCGGGGAGTGCCCCAAAGCCATTAATCTATGCCACCAGTAACTTAGCATCCGGTGTACCGAGCAGATTTTCGGGGTCGGGGTCGGGAACAGACTTCACACTCACCATATCGCGGTTAGAGCCGGAGGACTTCGCAACATATTATTGCCAGCAGTGGACATCGAACCCGCCAACATTTGGTGGCGGGACAAAAGTAGAAATCAAA"
--            , OligSplitting
--                  [(0, 58), (58, 116), (116, 174), (174, 232), (232, 290)]
--                  [(29, 87), (87, 145), (145, 203), (203, 261), (261, 318)])
--     -- ----------
--     ,( "GATATCGTATTAACCCAATCGCCAGGAACACTGAGTTTATCGCCAGGAGAAGGCGTAACCCTGAGTTGTCGGGCATCGAGTAGTGTCAGTTATATACACTGGTATCAGCAGAAGCCAGGGCAGGCACCGCGGTTATTAATATATGCCACAAGTAACTTAGCCTCGGGGATACCAGACAGATTCTCGGGATCGGGATCGGGGACCGACTTCACACTGACAATAAGTAGACTGGAACCAGAGGACTTCGCCGTCTACTACTGTCAACAATGGACCAGTAACCCTCCGACCTTCGGCGGCGGGACCAAGGTAGAAATAAAG"
--       , OligSplitting
--             [(0,58), (58,116), (116,174), (174,232), (232,290)]
--             [(29,87), (87,145), (145,203), (203,261), (261,318)])
--     ,( "GATATAGTACTGACACAATCGCCGGGAACCTTATCGCTGTCGCCTGGGGAAGGCGTAACCCTGTCGTGTCGGGCATCGTCGAGTGTATCGTACATCCATTGGTATCAACAGAAGCCAGGACAAGCTCCGAGATTACTGATCTATGCAACCAGTAACTTAGCCTCGGGTATACCGGACAGATTCTCGGGGTCGGGAAGTGGGACCGATTTCACCTTAACAATAAGTCGGTTAGAGCCGGAAGACTTTGCAGTCTACTACTGTCAGCAGTGGACCAGTAACCCGCCGACTTTTGGCGGCGGAACAAAAGTCGAAATAAAA"
--             , OligSplitting
--                   [(0,58), (58,116), (116,174), (174,232), (232,290)]
--                   [(29,87), (87,145), (145,203), (203,261), (261,318)])
--     ,( "GACATCGTCTTAACCCAAAGTCCAGGGACCCTGAGTCTGAGTCCTGGAGAAGGTGTAACCCTGAGTTGTCGGGCCTCGTCGAGTGTATCCTACATACACTGGTATCAACAGAAACCAGGACAAGCACCACGCTTATTAATCTACGCAACGAGTAATCTGGCCTCGGGAATACCAGATAGGTTTTCGGGTTCGGGGAGTGGGACAGATTTCACCTTAACCATCAGTAGACTGGAACCGGAGGACTTCGCAGTCTACTATTGTCAGCAGTGGACCAGTAACCCGCCAACATTCGGAGGCGGAACCAAGGTCGAAATCAAA"
--            , OligSplitting
--                  [(0, 58), (58, 116), (116, 174), (174, 232), (232, 290)]
--                  [(29, 87), (87, 145), (145, 203), (203, 261), (261, 318)])
--     -- ----------
--     ,( "CAAGTTCAACTTGTGGAATCAGGTGGCGGCTTAGTCCAACCAGGAGGGTCACTTACATTATCATGCACAGCTTCGGGATTCACCCTCGACCACTATGACATCGGCTGGTTCAGGCAAGCCCCAGGGAAAGAGAGAGAGGGTGTGTCCTGTATAAACAACTCCGATGATGACACCTATTATGCCGACAGCGTAAAAGGCCGGTTCACCATCTTCATGAACAACGCCAAAGACACCGTCTATTTGCAGATGAACTCCCTCAAGCCCGAAGACACTGCTATCTATTATTGTGCGGAGGCACGCGGGTGTAAGCGTGGGAGGTATGAATATGACTTTTGGGGACAAGGGACCCAGGTGACTGTCTCATCC"
--       , OligSplitting
--            [(0, 57), (57, 114), (114, 171), (171, 228), (228, 285), (285, 342)]
--            [(29, 86), (86, 143), (143, 200), (200, 257), (257, 314), (314, 366)])
--     ,( "CAAGTTCAGCTGGTTGAAAGCGGCGGAGGATTAGTGCAACCTGGCGGATCTTTAACTTTATCATGCACAGCCTCTGGCTTCACACTAGACCATTATGATATTGGGTGGTTCCGGCAGGCACCCGGAAAAGAACGAGAGGGTGTATCCTGTATCAACAATTCTGACGACGACACATACTATGCGGACTCGGTCAAGGGCCGCTTTACCATCTTCATGAACAACGCGAAGGACACTGTGTATCTCCAGATGAATTCGCTCAAGCCTGAGGATACCGCTATCTACTACTGCGCAGAAGCCCGTGGGTGTAAGAGGGGCAGATACGAGTATGACTTTTGGGGACAGGGGACCCAGGTCACAGTGAGTTCT"
--             , OligSplitting
--                  [(0, 57), (57, 114), (114, 171), (171, 228), (228, 285), (285, 342)]
--                  [(29, 86), (86, 143), (143, 200), (200, 257), (257, 314), (314, 366)])
--     ,( "CAAGTCCAACTCGTGGAAAGCGGTGGTGGTTTAGTTCAGCCTGGCGGGTCATTAACTCTCTCTTGCACGGCATCTGGATTCACCTTAGATCACTATGACATAGGCTGGTTCCGTCAGGCCCCAGGAAAAGAAAGGGAGGGCGTAAGTTGTATCAATAACAGTGACGACGACACCTACTACGCAGACAGCGTTAAAGGCCGGTTCACTATCTTCATGAACAACGCCAAGGATACAGTCTACCTTCAGATGAACTCGCTGAAGCCGGAGGATACTGCTATCTACTACTGCGCTGAGGCTCGCGGATGTAAACGGGGACGATATGAGTACGACTTTTGGGGTCAGGGCACTCAAGTGACGGTTTCTTCC"
--            , OligSplitting
--                  [(0, 57), (57, 114), (114, 171), (171, 228), (228, 285), (285, 342)]
--                  [(29, 86), (86, 143), (143, 200), (200, 257), (257, 314), (314, 366)])
--     -- ----------
--     ,( "TCGGTACTGCACCTGGTGCCAATAAACGCCACCAGTAAAGACGATTCAGATGTCACAGAAGTAATGTGGCAACCGGCCCTGAGGCGAGGGAGGGGTTTACAAGCACAAGGGTACGGGGTCAGAATCCAAGATGCCGGGGTCTATCTGCTGTATAGTCAGGTACTGTTTCAAGACGTCACCTTTACGATGGGACAGGTAGTAAGTAGAGAGGGACAAGGAAGGCAGGAAACCCTGTTCCGGTGTATAAGATCGATGCCATCGCATCCAGATAGAGCTTATAACTCGTGCTATAGTGCAGGAGTATTTCACCTGCACCAAGGAGATATACTGTCGGTCATAATACCGAGGGCACGGGCAAAACTGAATCTCAGTCCACACGGCACATTCCTGGGGTTCGTGAAACTGAGTGGTGGTGGGAGTGATCCG"
--       , OligSplitting
--            [(0,57), (57,114), (114,171), (171,228), (228,285), (285,342), (342,399)]
--            [(29,86), (86,143), (143,200), (200,257), (257,314), (314,371), (371,426)])
--     ,( "TCGGTATTACATCTGGTCCCAATCAACGCAACCTCCAAGGACGACAGTGATGTGACAGAAGTAATGTGGCAACCAGCCCTTAGACGCGGAAGGGGACTTCAGGCACAGGGGTACGGGGTAAGAATACAAGACGCAGGAGTCTACCTGCTGTACTCGCAGGTACTGTTTCAAGACGTCACTTTTACTATGGGACAAGTCGTAAGTCGGGAAGGACAAGGGAGACAAGAGACACTGTTCAGGTGCATCAGATCTATGCCGTCGCACCCAGACAGGGCATACAACAGTTGTTATTCGGCCGGGGTATTTCACTTACACCAAGGGGATATACTGTCCGTCATCATACCGAGAGCCAGAGCCAAACTGAACCTCTCGCCGCATGGGACATTTTTAGGATTTGTAAAATTGTCTGGTGGTGGGTCTGATCCG"
--             , OligSplitting
--                  [(0,57), (57,114), (114,171), (171,228), (228,285), (285,342), (342,399)]
--                  [(29,86), (86,143), (143,200), (200,257), (257,314), (314,371), (371,426)])
--
--     ,( "AGTGTGCTGCACTTAGTACCGATTAACGCCACCAGTAAGGATGATTCGGACGTCACAGAAGTCATGTGGCAACCGGCATTACGGCGGGGTAGGGGATTACAGGCACAAGGGTATGGGGTAAGAATCCAAGACGCCGGAGTCTACTTACTGTACTCGCAGGTGCTGTTCCAAGATGTCACCTTCACAATGGGTCAAGTCGTCTCTCGGGAAGGACAGGGAAGACAGGAAACATTATTTCGTTGCATCCGGTCTATGCCGTCGCACCCAGATCGGGCATACAATAGTTGCTATAGTGCAGGAGTCTTCCATCTGCACCAGGGAGACATACTGTCGGTCATAATCCCGCGGGCAAGAGCCAAGTTAAACTTAAGTCCGCATGGAACCTTCTTAGGATTTGTAAAGTTAAGTGGCGGTGGGAGTGACCCA"
--            , OligSplitting
--                  [(0,57), (57,114), (114,171), (171,228), (228,285), (285,342), (342,399)]
--                  [(29,86), (86,143), (143,200), (200,257), (257,314), (314,371), (371,426)])
--     -- ----------
--     ,( "GAAGTTCAGCTAGTCCAATCTGGTGGTGGTTTAGTTCAGCCCGGTGGTTCCCTGCGACTGTCTTGTGCGGCTTCCGGTTTTACATTTGACGATGAAGCTATGAGTTGGGTTCGGCAAGCGCCAGGTAAAGGTCTGGAGTGGGTGTCCTCCATAAGTAGAAACGGCGGTTGCACGTATTACGCTATCAGTATGAAGGGTAGATTCACGATCTCCAGGGACAACGCGAAGAACACACTATATCTCCAGATGAACTCCCTGAAGAGTGAGGACACGGCGGTGTACTACTGTGCAAAGGATAGACCAGGCTACTACAGTGATCTAGTCGGTGTCGATTACTGGGGTCAAGGCACACTGGTTACAGTCTCCAGT"
--            , OligSplitting
--                  [(0,57), (57,114), (114,171), (171,228), (228,285), (285,342)]
--                  [(29,86), (86,143), (143,200), (200,257), (257,314), (314,369)])
--     ,( "GAGGTCCAATTAGTCCAGTCAGGCGGTGGTCTAGTCCAACCAGGCGGCTCCTTACGTCTAAGTTGCGCTGCGTCCGGGTTCACATTCGACGACGAAGCTATGAGTTGGGTTAGACAAGCTCCAGGCAAGGGTTTAGAGTGGGTCTCCAGTATCAGTCGTAACGGCGGCTGTACCTACTATGCTATATCCATGAAAGGTCGGTTCACGATAAGTCGTGACAACGCCAAGAATACACTGTACTTACAGATGAACAGTCTAAAGTCCGAAGACACGGCTGTGTATTACTGTGCCAAAGATCGTCCAGGCTATTATTCCGACTTAGTTGGTGTCGATTACTGGGGCCAGGGCACGCTGGTTACAGTCAGTTCC"
--       , OligSplitting
--             [(0,57), (57,114), (114,171), (171,228), (228,285), (285,342)]
--             [(29,86), (86,143), (143,200), (200,257), (257,314), (314,369)])
--     ,( "GAAGTCCAATTAGTTCAAAGTGGCGGTGGATTAGTCCAACCCGGCGGCAGTCTACGTTTAAGTTGCGCGGCGTCCGGCTTCACGTTCGATGACGAAGCTATGTCTTGGGTCCGTCAGGCTCCAGGCAAAGGCCTAGAATGGGTTTCCTCTATATCTCGGAATGGTGGCTGCACGTACTATGCGATCAGTATGAAGGGCCGGTTCACGATCAGTCGCGATAACGCTAAGAACACACTGTATCTGCAAATGAACTCCCTGAAGAGTGAGGATACAGCGGTCTACTACTGTGCGAAGGACAGACCAGGCTACTACTCCGACCTAGTCGGTGTTGATTATTGGGGTCAAGGTACATTAGTTACGGTTAGTAGT"
--       , OligSplitting
--            [(0,57), (57,114), (114,171), (171,228), (228,285), (285,342)]
--            [(29,86), (86,143), (143,200), (200,257), (257,314), (314,369)])
--     -- ----------
--     ,( "GAAGTCCAGTTAGTAGAGTCGGGAGGCGGATTGGTACAACCAGGAGGCAGTTTAAGACTGTCGTGCGCAGCAAGTGGATTCACCTTCGATGACTACTGGATGAGTTGGGTAAGGCAAGCACCAGGAAAGGGGTTAGAGTGGGTAGCCAATATCTCGTGGAACAGTGGGTCGAAGTATTACGTGGATTCGGTAAAAGGAAGGTTCACCATCTCGCGGGACAACGCAAAGAACTCGCTGTACTTACAAATGAATAGTCTGAGGGCAGAGGACACCGCCGTATATTATTGCGCCAGAGACAATTCGGGGTACGGACACTATTACTACGGGATGGACGTATGGGGCCAAGGGACCCTGGTAACAGTATCCTCG"
--       , OligSplitting
--            [(0,57), (57,114), (114,171), (171,228), (228,285), (285,342)]
--            [(29,86), (86,143), (143,200), (200,257), (257,314), (314,369)])
--     ,( "GAAGTACAACTGGTAGAGAGTGGTGGAGGATTAGTACAACCAGGTGGATCGCTGAGATTATCGTGCGCAGCAAGTGGATTCACATTCGACGATTACTGGATGTCGTGGGTCAGACAGGCCCCGGGAAAGGGTTTAGAATGGGTCGCCAACATCAGTTGGAACAGTGGATCGAAATATTATGTAGACTCGGTCAAAGGGCGGTTCACCATCTCGCGGGATAACGCAAAGAATTCGCTGTACTTACAAATGAATTCCCTGCGGGCAGAAGACACCGCAGTATACTATTGCGCACGGGATAACTCGGGGTACGGGCACTATTACTACGGAATGGATGTATGGGGCCAGGGAACCCTCGTCACCGTAAGCTCG"
--             , OligSplitting
--                  [(0,57), (57,114), (114,171), (171,228), (228,285), (285,342)]
--                  [(29,86), (86,143), (143,200), (200,257), (257,314), (314,369)])
--     ,( "GAAGTCCAGCTGGTCGAATCAGGCGGAGGATTAGTACAACCAGGAGGATCGTTACGGTTATCATGCGCCGCATCGGGATTCACCTTTGACGATTATTGGATGAGTTGGGTACGGCAAGCACCAGGAAAGGGCCTGGAATGGGTCGCCAATATCTCGTGGAACAGTGGATCGAAGTACTATGTTGACTCGGTCAAGGGAAGGTTTACCATATCGCGGGACAACGCAAAAAACAGTCTGTATCTGCAAATGAACAGTTTAAGAGCCGAGGACACCGCCGTCTATTACTGCGCCAGAGATAACTCGGGTTATGGACATTACTACTATGGGATGGATGTGTGGGGACAGGGGACCCTGGTAACAGTCAGCTCG"
--            , OligSplitting
--                  [(0,57), (57,114), (114,171), (171,228), (228,285), (285,342)]
--                  [(29,86), (86,143), (143,200), (200,257), (257,314), (314,369)])
--     -- ----------
--     ,( "CAGGTACAATTGCAAGAAAGCGGCGGAGGACTCGTACAACCCGGAGGATCTCTTAGACTAAGTTGTGCTGCATCCGGCATCCAGTTCAAGTTCCACAATATGGGTTGGGGACGGCAAGCTCCAGGAAAACAACGCGAACATGTAGCCGCAATGGATCATGGAAGGCGGACAATATATGCTGATCACGTTAAGGGTCGCTTTACTATTAGCCGAGATAACACGCGCAACACCGTGTACTTACAAATGAACAGCCTGAAAGCCGAGGACACCGCGATCTATTATTGTAAGGCATCCGCAGGTAGGCGAGTATATTGGGGTCAGGGCACGATGGTCACGGTCAGTTCG"
--       , OligSplitting
--            [(0,53), (53,106), (106,159), (159,212), (212,265), (265,318)]
--            [(27,80), (80,133), (133,186), (186,239), (239,292), (292,345)])
--     ,( "CAAGTTCAGTTACAAGAGTCCGGCGGAGGTTTAGTCCAACCAGGTGGCTCTCTGAGACTCTCTTGTGCCGCGTCAGGAATCCAGTTTAAGTTCCACAACATGGGCTGGGGAAGACAGGCTCCAGGAAAACAACGCGAACACGTAGCCGCTATGGATCACGGAAGGCGTACAATCTATGCTGATCATGTCAAGGGACGCTTCACCATTTCTAGGGACAATACTCGCAATACAGTCTACCTCCAGATGAACTCCCTCAAAGCAGAGGACACGGCAATCTATTATTGTAAGGCAAGTGCAGGCCGGAGGGTATATTGGGGCCAGGGTACAATGGTGACAGTCTCAAGT"
--             , OligSplitting
--                  [(0,53), (53,106), (106,159), (159,212), (212,265), (265,318)]
--                  [(27,80), (80,133), (133,186), (186,239), (239,292), (292,345)])
--     ,( "CAAGTGCAGTTACAAGAAAGCGGAGGAGGATTAGTCCAGCCAGGTGGCAGTCTGCGGTTAAGTTGCGCAGCTAGTGGTATCCAGTTTAAGTTCCATAACATGGGGTGGGGACGGCAGGCCCCAGGGAAACAGAGGGAACACGTAGCAGCAATGGATCATGGAAGGAGAACAATCTATGCCGATCATGTCAAGGGACGTTTCACAATTTCCCGCGATAATACCAGAAACACTGTGTATCTCCAGATGAACAGCTTGAAGGCTGAAGACACCGCAATCTACTACTGTAAGGCCTCCGCTGGCAGAAGAGTATACTGGGGCCAAGGTACGATGGTGACGGTAAGTTCG"
--            , OligSplitting
--                  [(0,53), (53,106), (106,159), (159,212), (212,265), (265,318)]
--                  [(27,80), (80,133), (133,186), (186,239), (239,292), (292,345)])
--     -- ----------
--     ,( "GAAATTGTAATGACACAAAGTCCTGCCACCCTATCCCTCAGCCCAGGAGAGCGTGCTACGTTAAGCTGCCGAGCAAGTCAGGATATCAGCAAGTATCTCAACTGGTATCAACAGAAGCCAGGACAGGCCCCTCGCCTACTGATCTATCATACATCAAGACTGCATTCCGGCATACCCGCGAGGTTTTCTGGAAGCGGGTCCGGCACGGACTACACATTGACAATATCCAGTCTGCAACCAGAAGATTTTGCCGTGTACTTCTGTCAGCAGGGTAACACGTTGCCTTACACCTTCGGACAAGGTACTAAGTTAGAGATCAAAGGTGGAGGTGGCTCCGGTGGTGGCGGCTCTGGAGGAGGAGGAAGCGGAGGCGGTGGTAGCCAGGTGCAACTACAGGAATCCGGGCCAGGTTTGGTCAAGCCTTCTGAAACGTTATCCCTAACCTGCACCGTAAGTGGAGTCTCTTTACCCGATTATGGTGTATCATGGATACGCCAGCCACCAGGAAAAGGCTTAGAATGGATAGGTGTGATCTGGGGCTCCGAGACCACTTACTATAACTCATCCCTCAAATCAAGGGTTACGATCAGCAAAGACAACTCCAAGAATCAGGTGTCTCTGAAGCTGAGCAGCGTAACTGCCGCCGATACAGCCGTGTACTATTGTGCAAAACACTATTATTACGGAGGGTCATATGCAATGGACTATTGGGGACAGGGTACTCTGGTCACAGTGTCCAGT"
--       , OligSplitting
--            [(0,59), (59,118), (118,177), (177,236), (236,295), (295,354), (354,413), (413,472), (472,531), (531,590), (590,649), (649,708)]
--            [(30,89), (89,148), (148,207), (207,266), (266,325), (325,384), (384,443), (443,502), (502,561), (561,620), (620,679), (679,741)])
--     ,( "GAAATAGTGATGACCCAATCACCCGCCACTCTGTCATTATCCCCTGGGGAACGGGCAACTCTAAGCTGTAGGGCATCTCAAGATATCTCCAAGTACCTCAACTGGTATCAGCAGAAACCAGGGCAAGCTCCGCGTCTCCTGATATATCACACCTCTCGGCTCCACAGTGGGATTCCTGCTAGGTTCTCTGGTTCAGGCTCAGGCACCGACTACACCCTGACTATCTCGTCATTACAGCCCGAAGACTTTGCCGTTTACTTTTGTCAGCAGGGCAACACGCTGCCGTATACTTTCGGGCAGGGCACGAAATTAGAGATAAAGGGCGGAGGCGGCAGCGGCGGAGGCGGATCAGGTGGTGGAGGGTCCGGCGGAGGCGGAAGTCAGGTCCAGTTACAAGAATCAGGCCCGGGTTTGGTTAAACCCTCTGAAACATTATCTCTTACCTGCACTGTTTCAGGAGTATCCCTGCCAGATTACGGTGTGAGCTGGATTCGACAACCTCCTGGAAAGGGATTAGAGTGGATCGGTGTGATATGGGGATCTGAAACAACCTACTACAACTCCTCACTCAAGTCCAGAGTGACAATCTCTAAGGATAACTCAAAGAATCAAGTTTCTCTGAAATTGAGCAGTGTCACAGCTGCTGATACAGCAGTCTACTATTGTGCTAAGCACTATTACTATGGCGGAAGTTATGCTATGGACTATTGGGGTCAGGGCACTCTGGTGACAGTGTCCAGT"
--             , OligSplitting
--                  [(0,59), (59,118), (118,177), (177,236), (236,295), (295,354), (354,413), (413,472), (472,531), (531,590), (590,649), (649,708)]
--                  [(30,89), (89,148), (148,207), (207,266), (266,325), (325,384), (384,443), (443,502), (502,561), (561,620), (620,679), (679,741)])
--     ,( "GAAATCGTAATGACACAAAGCCCCGCAACCCTATCATTGTCTCCAGGCGAACGCGCTACCCTGTCTTGCAGAGCCTCACAGGACATTAGTAAGTATCTGAACTGGTATCAACAAAAGCCAGGTCAGGCTCCCCGCTTACTGATCTACCACACCAGTCGGTTACATTCGGGAATTCCAGCGAGGTTTAGTGGTAGTGGAAGTGGTACTGATTATACCCTCACCATCTCCTCACTGCAACCCGAGGACTTTGCGGTATACTTCTGTCAGCAGGGAAACACATTGCCGTACACTTTCGGGCAAGGAACTAAACTGGAAATCAAAGGCGGAGGAGGCAGTGGAGGAGGTGGCAGCGGCGGAGGAGGAAGTGGAGGAGGAGGATCTCAGGTACAGTTACAGGAATCCGGTCCAGGTCTCGTAAAACCATCTGAAACCCTCAGCCTCACGTGTACCGTGTCCGGTGTCTCTCTCCCAGATTATGGTGTGTCTTGGATTCGGCAACCGCCCGGGAAAGGTTTGGAGTGGATCGGGGTTATTTGGGGCAGTGAGACAACCTATTACAACTCCTCCCTGAAGTCTAGGGTAACAATAAGTAAAGATAATTCCAAGAATCAGGTCAGCCTGAAGCTGAGTTCTGTCACTGCTGCTGATACCGCAGTTTACTATTGCGCTAAACATTATTACTATGGTGGCAGTTACGCGATGGATTATTGGGGACAAGGGACCCTGGTGACGGTGTCGTCC"
--            , OligSplitting
--                  [(0,59), (59,118), (118,177), (177,236), (236,295), (295,354), (354,413), (413,472), (472,531), (531,590), (590,649), (649,708)]
--                  [(30,89), (89,148), (148,207), (207,266), (266,325), (325,384), (384,443), (443,502), (502,561), (561,620), (620,679), (679,741)])
--     -- ----------
--     ,( "GAAATCGTCATGACCCAGTCGCCTGCTACACTGAGTCTCTCTCCCGGAGAACGTGCTACTTTGAGCTGTCGCGCCTCTCAGGATATCTCCAAGTACCTGAACTGGTATCAACAGAAGCCTGGTCAAGCTCCCCGTTTACTGATCTATCATACAAGTAGGCTGCATTCCGGGATTCCAGCCCGGTTCTCTGGTTCTGGGTCAGGCACTGATTACACACTCACCATTAGTTCTCTCCAGCCTGAAGACTTCGCCGTGTATTTCTGTCAGCAGGGGAACACACTGCCTTACACTTTCGGGCAGGGCACAAAGCTCGAAATTAAAGGAGGAGGAGGAAGTGGCGGCGGTGGCTCACAGGTTCAACTCCAAGAGTCAGGGCCTGGGTTAGTAAAACCCTCAGAAACACTTAGCTTAACGTGTACCGTCAGTGGTGTTAGCCTCCCTGACTATGGCGTGTCCTGGATACGGCAACCGCCTGGAAAGGGATTAGAATGGATCGGTGTTATCTGGGGCTCCGAGACGACCTACTACAATAGCAGTCTGAAGTCTCGGGTGACAATATCCAAGGATAATTCAAAGAACCAAGTATCCTTGAAGCTGTCCTCGGTCACAGCTGCTGACACAGCTGTATACTATTGCGCCAAACATTACTATTACGGCGGGTCATATGCTATGGATTACTGGGGACAAGGAACACTGGTTACAGTCTCCTCC"
--       , OligSplitting
--            [(0,57), (57,114), (114,171), (171,228), (228,285), (285,342), (342,399), (399,456), (456,513), (513,570), (570,627), (627,684)]
--            [(29,86), (86,143), (143,200), (200,257), (257,314), (314,371), (371,428), (428,485), (485,542), (542,599), (599,656), (656,711)])
--     ,( "GAGATCGTGATGACGCAAAGTCCAGCCACTCTTAGTCTGAGCCCAGGTGAACGAGCTACACTGTCTTGCAGAGCCTCACAGGATATCTCCAAGTATCTTAATTGGTATCAGCAGAAGCCAGGGCAAGCGCCACGCCTTCTCATATACCACACTTCTAGGCTGCACAGCGGTATCCCCGCTCGTTTTTCTGGGTCTGGCTCAGGAACAGACTACACCTTGACCATTTCCTCGCTCCAACCAGAAGATTTCGCGGTGTACTTTTGTCAACAGGGGAATACCCTCCCTTATACCTTCGGCCAGGGTACTAAGTTGGAAATTAAAGGAGGCGGCGGCTCCGGTGGCGGAGGCTCCCAAGTGCAGCTACAGGAAAGCGGTCCCGGCCTGGTCAAACCTAGTGAAACTCTCTCATTAACATGCACCGTCTCTGGCGTGAGCCTGCCCGACTACGGAGTTTCTTGGATACGTCAGCCACCCGGGAAGGGATTAGAATGGATCGGAGTCATTTGGGGAAGTGAGACTACTTACTACAACTCTAGTCTGAAGTCCAGAGTGACCATCTCTAAGGACAATTCTAAAAATCAGGTTTCCCTTAAGTTGTCGTCAGTGACCGCAGCTGATACCGCAGTCTACTATTGTGCAAAACATTATTACTATGGCGGGTCTTATGCTATGGACTACTGGGGACAGGGGACATTAGTTACCGTGTCTTCC"
--             , OligSplitting
--                  [(0,57), (57,114), (114,171), (171,228), (228,285), (285,342), (342,399), (399,456), (456,513), (513,570), (570,627), (627,684)]
--                  [(29,86), (86,143), (143,200), (200,257), (257,314), (314,371), (371,428), (428,485), (485,542), (542,599), (599,656), (656,711)])
--     ,( "GAGATAGTAATGACACAGAGTCCCGCAACACTCAGTCTGAGCCCCGGAGAAAGAGCTACCCTGAGCTGTAGGGCAAGTCAAGATATCAGCAAATACCTCAACTGGTATCAACAAAAGCCAGGACAGGCACCTCGTCTCTTAATCTATCACACAAGCAGGCTGCATAGCGGTATTCCCGCCAGGTTTTCTGGAAGTGGTTCTGGCACCGACTATACTCTGACCATCAGCTCCCTGCAACCCGAAGATTTCGCCGTTTACTTTTGTCAGCAAGGAAACACACTCCCCTATACCTTTGGGCAGGGCACAAAGCTGGAAATTAAGGGTGGAGGCGGCAGCGGAGGTGGCGGATCTCAAGTACAGCTTCAGGAGAGTGGACCAGGACTTGTCAAACCATCTGAAACCCTGTCTCTTACGTGTACGGTAAGCGGTGTAAGTCTCCCAGATTACGGGGTGAGTTGGATCAGGCAGCCACCAGGAAAGGGATTGGAGTGGATTGGTGTAATCTGGGGTAGTGAGACTACCTACTACAACAGCAGTCTGAAGAGCAGAGTGACCATCTCTAAGGACAACAGTAAAAATCAGGTCAGCCTCAAGTTGAGCTCTGTTACAGCGGCCGACACAGCTGTGTACTATTGCGCCAAACATTATTACTACGGCGGTTCCTATGCTATGGACTATTGGGGCCAAGGGACACTGGTGACTGTGAGCTCC"
--            , OligSplitting
--                  [(0,57), (57,114), (114,171), (171,228), (228,285), (285,342), (342,399), (399,456), (456,513), (513,570), (570,627), (627,684)]
--                  [(29,86), (86,143), (143,200), (200,257), (257,314), (314,371), (371,428), (428,485), (485,542), (542,599), (599,656), (656,711)])
--     -- ----------
--     ,( "GATATTCAAATGACTCAGACTACGTCGTCTTTGTCTGCATCCTTGGGAGATCGCGTTACTATTTCCTGCCGCGCATCGCAGGATATTAGCAAGTATCTCAATTGGTATCAGCAGAAACCCGACGGAACCGTGAAGCTGCTCATATACCACACCAGCCGTTTGCATTCCGGGGTGCCTTCCAGGTTCAGTGGCAGCGGATCTGGAACTGACTACTCACTCACCATATCAAATCTGGAGCAGGAAGATATCGCCACCTACTTCTGTCAGCAGGGAAACACACTGCCGTACACTTTTGGAGGTGGAACTAAGCTGGAGATTACAGGCTCAACTTCCGGCTCTGGCAAGCCAGGCAGCGGGGAGGGAAGTACTAAGGGTGAGGTCAAGTTATGGGAGAGCGGTCCAGGACTGGTGGCCCCTAGTCAGAGCCTTAGCGTTACATGCACAGTTTCCGGGGTTTCTCTGCCCGACTACGGAGTGTCATGGATAAGACAACCACCGCGCAAAGGTCTCGAATGGCTGGGTGTAATATGGGGCTCCGAGACCACATATTATAATTCCGCTCTCAAGTCCCGCCTGACAATTATCAAGGACAACAGCAAGTCACAGGTGTTCCTTAAAATGAACAGTCTGCAAACTGACGACACAGCTATATACTATTGTGCTCGACACTACTACTACGGCGGCAGTTATGCTATGGATTACTGGGGACAAGGCACCAGCGTCACGGTTTCGTCT"
--       , OligSplitting
--            [(0,59), (59,118), (118,177), (177,236), (236,295), (295,354), (354,413), (413,472), (472,531), (531,590), (590,649), (649,708)]
--            [(30,89), (89,148), (148,207), (207,266), (266,325), (325,384), (384,443), (443,502), (502,561), (561,620), (620,679), (679,735)])
--     ,( "GACATACAAATGACTCAAACAACCAGCAGCCTTTCAGCATCCCTTGGCGACCGCGTTACTATTTCGTGTCGTGCATCACAGGACATATCTAAGTACCTGAATTGGTATCAGCAGAAACCGGATGGAACAGTGAAGCTCTTGATATACCACACATCAAGACTGCACTCAGGAGTCCCCTCACGGTTTTCAGGATCTGGGAGCGGGACCGACTACTCCCTGACGATTAGCAACTTAGAGCAGGAGGACATAGCTACCTACTTCTGCCAGCAAGGCAATACATTACCCTATACTTTTGGCGGCGGGACTAAGTTAGAGATCACCGGAAGTACAAGCGGTAGTGGGAAGCCAGGCAGTGGGGAAGGATCTACTAAAGGAGAAGTGAAGCTGTGGGAGTCAGGACCTGGCTTAGTTGCTCCATCCCAAAGTCTGAGTGTAACATGCACAGTTTCTGGCGTCTCCTTGCCCGACTATGGAGTGTCATGGATTAGACAGCCTCCGCGCAAGGGCTTAGAATGGCTGGGTGTGATCTGGGGTTCCGAAACAACCTACTATAACAGCGCCCTGAAGAGCAGACTGACGATTATCAAAGACAACTCCAAGAGCCAGGTGTTCCTGAAGATGAACAGCCTGCAAACCGACGACACCGCTATCTATTACTGTGCCCGCCACTACTACTACGGAGGCTCCTATGCAATGGACTACTGGGGTCAGGGGACATCAGTCACAGTTAGCAGC"
--             , OligSplitting
--                  [(0,59), (59,118), (118,177), (177,236), (236,295), (295,354), (354,413), (413,472), (472,531), (531,590), (590,649), (649,708)]
--                  [(30,89), (89,148), (148,207), (207,266), (266,325), (325,384), (384,443), (443,502), (502,561), (561,620), (620,679), (679,735)])
--     ,( "GATATTCAGATGACTCAGACTACCTCTTCTCTGAGTGCTTCTCTGGGAGACCGCGTCACCATAAGCTGTAGGGCCTCTCAGGATATTAGCAAGTACCTAAACTGGTATCAACAGAAGCCCGACGGCACTGTCAAACTGCTCATCTACCATACTTCCCGTCTGCATAGCGGTGTCCCATCAAGGTTCAGTGGAAGTGGAAGTGGAACAGACTACAGCCTGACCATCTCAAACCTTGAGCAGGAAGATATCGCTACATATTTTTGTCAACAGGGTAACACATTGCCGTACACCTTTGGCGGCGGCACCAAGTTAGAAATCACTGGTTCTACATCTGGAAGTGGAAAGCCTGGTAGTGGGGAAGGTTCGACAAAGGGTGAGGTGAAGCTGTGGGAAAGTGGACCAGGTCTCGTCGCACCTTCTCAATCGTTAAGTGTAACTTGCACTGTCAGCGGCGTGAGCCTGCCGGATTACGGTGTCAGTTGGATTAGACAGCCTCCACGCAAGGGCTTAGAGTGGCTGGGCGTAATCTGGGGATCGGAGACGACATACTATAATAGTGCCCTCAAGTCTCGGCTGACAATCATCAAGGACAACAGCAAGTCCCAGGTATTCCTCAAGATGAACTCACTTCAGACGGACGACACAGCTATCTACTACTGTGCCAGGCACTACTACTACGGAGGAAGTTACGCTATGGATTACTGGGGACAGGGCACCTCCGTGACCGTGAGCTCA"
--            , OligSplitting
--                  [(0,59), (59,118), (118,177), (177,236), (236,295), (295,354), (354,413), (413,472), (472,531), (531,590), (590,649), (649,708)]
--                  [(30,89), (89,148), (148,207), (207,266), (266,325), (325,384), (384,443), (443,502), (502,561), (561,620), (620,679), (679,735)])
--     -- ----------
--     ,( "GCAGAACCTAAGTCTCCCGACAAGACACACACTTGCCCTCCCTGCCCTGCTCCTCCTGTGGCTGGTCCTAGTGTGTTTTTGTTCCCGCCGAAGCCCAAAGATACACTTATGATTGCACGTACACCTGAAGTGACATGCGTTGTGGTGGACGTGAGCCATGAAGACCCCGAAGTGAAGTTTAACTGGTACGTGGACGGCGTTGAGGTGCATAATGCAAAGACGAAGCCTCGGGAAGAACAGTATAACTCCACTTACCGTGTCGTAAGCGTGCTGACTGTACTGCACCAAGACTGGCTCAACGGTAAAGAGTACAAGTGCAAGGTGTCAAATAAGGCTCTGCCAGCTCCAATAGAGAAGACGATTTCGAAGGCCAAAGGACAGCCTCGCGAACCTCAGGTCTATACTCTTCCTCCTTCCCGCGACGAGCTGACCAAGAACCAGGTCTCATTGACTTGCCTGGTGAAGGGCTTTTACCCAAGTGATATCGCTGTGGAGTGGGAAAGTAATGGTCAACCGGAGAATAACTATAAGACAACCCCACCAGTCCTCGACTCGGACGGCTCGTTCTTCCTGTACTCTAAACTTACAGTGGACAAGTCTCGATGGCAGCAAGGGAATGTTTTCTCGTGCTCCGTGATGCACGAAGCTCTTCACAACCACTACACACAAAAGAGCCTTTCTTTGAGCCCAGGGAAGAAAGATCCCAAA"
--       , OligSplitting
--            [(0,57), (57,114), (114,171), (171,228), (228,285), (285,342), (342,399), (399,456), (456,513), (513,570), (570,627), (627,684)]
--            [(29,86), (86,143), (143,200), (200,257), (257,314), (314,371), (371,428), (428,485), (485,542), (542,599), (599,656), (656,708)])
--     ,( "GCAGAGCCAAAATCGCCTGATAAGACACATACTTGTCCTCCTTGCCCGGCTCCTCCTGTGGCCGGTCCTTCCGTATTTCTCTTCCCGCCTAAGCCCAAGGATACACTGATGATTGCAAGGACACCTGAAGTGACATGCGTGGTGGTAGACGTGTCCCATGAGGACCCTGAGGTGAAATTCAACTGGTATGTGGACGGGGTGGAGGTTCACAACGCTAAGACGAAGCCTAGGGAAGAGCAGTACAACTCCACTTATCGCGTGGTCTCCGTGCTGACCGTGTTACATCAGGACTGGCTGAACGGAAAAGAATACAAGTGCAAGGTGTCCAACAAAGCTCTACCTGCTCCCATTGAAAAAACCATATCTAAAGCAAAGGGACAGCCCAGGGAACCCCAAGTCTATACTTTACCTCCTTCCAGGGACGAACTGACCAAGAATCAAGTGTCACTTACCTGTTTAGTCAAGGGCTTCTACCCTTCGGATATCGCAGTGGAATGGGAGTCAAACGGCCAGCCTGAAAACAACTACAAGACTACTCCTCCGGTGCTAGACTCCGATGGCAGCTTCTTCCTGTATAGCAAGCTGACCGTAGACAAGTCCCGGTGGCAACAGGGGAATGTCTTTAGTTGCTCTGTCATGCACGAAGCCCTCCATAATCACTACACCCAGAAGAGTCTGTCCCTCTCTCCAGGGAAAAAAGATCCCAAG"
--             , OligSplitting
--                  [(0,57), (57,114), (114,171), (171,228), (228,285), (285,342), (342,399), (399,456), (456,513), (513,570), (570,627), (627,684)]
--                  [(29,86), (86,143), (143,200), (200,257), (257,314), (314,371), (371,428), (428,485), (485,542), (542,599), (599,656), (656,708)])
--     ,( "GCCGAGCCAAAAAGCCCCGACAAGACCCATACTTGTCCACCATGTCCGGCCCCACCTGTTGCAGGCCCTAGCGTGTTTCTGTTCCCTCCCAAACCGAAGGATACCCTGATGATCGCAAGAACGCCCGAGGTGACATGTGTTGTGGTGGACGTGTCACATGAAGATCCCGAGGTCAAGTTCAACTGGTACGTTGACGGAGTGGAAGTCCACAACGCCAAGACAAAACCCAGGGAGGAACAATATAACAGTACATACCGGGTGGTCAGTGTGCTTACAGTCCTGCACCAAGATTGGCTCAATGGCAAGGAATACAAGTGTAAGGTAAGCAACAAGGCACTTCCCGCACCCATTGAAAAGACCATATCCAAGGCCAAAGGGCAGCCACGTGAACCCCAGGTATACACTCTCCCGCCTAGCAGAGACGAACTCACGAAGAACCAGGTTTCCCTCACTTGTCTGGTGAAGGGATTTTATCCATCCGATATTGCTGTGGAGTGGGAATCCAACGGTCAACCAGAGAACAATTATAAAACTACCCCACCCGTGCTGGATTCGGATGGCAGCTTCTTCCTGTATTCTAAGCTGACAGTGGACAAATCTCGTTGGCAGCAGGGTAATGTGTTTTCATGCTCCGTTATGCACGAAGCACTCCATAATCACTATACCCAGAAGTCTCTGAGCCTGTCTCCAGGGAAAAAGGACCCTAAG"
--            , OligSplitting
--                  [(0,57), (57,114), (114,171), (171,228), (228,285), (285,342), (342,399), (399,456), (456,513), (513,570), (570,627), (627,684)]
--                  [(29,86), (86,143), (143,200), (200,257), (257,314), (314,371), (371,428), (428,485), (485,542), (542,599), (599,656), (656,708)])
--     -- ----------
--     ,( "TTCTGGGTACTTGTGGTCGTAGGCGGAGTGCTGGCATGCTACAGCTTACTGGTGACAGTTGCCTTCATAATCTTCTGGGTAAGAAGTAAGAGGAGTCGCTTACTCCATAGTGACTATATGAACATGACACCCAGAAGGCCAGGTCCTACCCGCAAACATTATCAGCCCTACGCTCCTCCAAGAGACTTTGCTGCTTACAGAAGCAGGGATCAGAGATTACCACCAGATGCCCATAAACCTCCTGGAGGCGGCAGCTTCAGAACCCCAATACAAGAAGAACAGGCCGATGCTCACAGTACCTTAGCTAAAATTCGAGTTAAGTTCAGTAGAAGTGCCGACGCACCTGCATATCAGCAAGGGCAAAATCAGCTTTACAACGAACTCAACCTGGGGAGACGAGAGGAGTATGACGTATTGGACAAGCGCAGAGGTCGCGATCCAGAGATGGGCGGCAAGCCCCGAAGGAAAAATCCACAGGAGGGATTATACAATGAACTCCAGAAGGACAAGATGGCCGAAGCCTATAGCGAAATTGGGATGAAGGGCGAACGTCGGCGGGGCAAGGGCCATGATGGACTTTATCAGGGCCTGTCCACAGCGACCAAAGACACATACGACGCTCTACACATGCAAGCATTACCACCTAGG"
--       , OligSplitting
--            [(0,56), (56,112), (112,168), (168,224), (224,280), (280,336), (336,392), (392,448), (448,504), (504,560), (560,616)]
--            [(28,84), (84,140), (140,196), (196,252), (252,308), (308,364), (364,420), (420,476), (476,532), (532,588), (588,648)])
--     ,( "TTCTGGGTGCTCGTAGTTGTGGGCGGCGTGCTCGCTTGTTATAGTCTGCTGGTAACGGTCGCCTTTATCATCTTCTGGGTGAGAAGTAAAAGAAGTAGGCTCCTACATTCTGACTACATGAATATGACACCAAGGCGTCCTGGCCCAACCCGAAAGCATTATCAGCCCTATGCACCTCCAAGGGATTTTGCCGCATACCGAAGTAGAGACCAAAGGCTGCCACCAGACGCTCACAAACCACCTGGTGGAGGTTCTTTTAGGACACCAATACAGGAGGAGCAGGCAGATGCACATTCCACACTGGCAAAAATTAGAGTAAAATTCTCTCGGAGTGCTGATGCCCCAGCTTACCAGCAAGGACAGAACCAGTTATATAACGAGCTTAACCTCGGACGCCGGGAGGAATACGACGTCTTAGACAAGCGCAGGGGACGTGACCCTGAGATGGGAGGAAAACCTAGACGGAAAAATCCTCAAGAGGGGCTCTATAATGAACTGCAAAAAGATAAGATGGCAGAGGCCTACTCCGAAATCGGAATGAAGGGCGAGAGACGACGCGGTAAGGGGCATGACGGCCTTTATCAGGGACTTTCCACCGCCACCAAAGATACTTATGACGCCCTTCATATGCAGGCTTTACCGCCAAGG"
--             , OligSplitting
--                  [(0,56), (56,112), (112,168), (168,224), (224,280), (280,336), (336,392), (392,448), (448,504), (504,560), (560,616)]
--                  [(28,84), (84,140), (140,196), (196,252), (252,308), (308,364), (364,420), (420,476), (476,532), (532,588), (588,648)])
--     ,( "TTCTGGGTTTTGGTTGTGGTGGGCGGAGTCCTCGCGTGTTACAGCTTGTTAGTCACAGTCGCATTCATCATATTCTGGGTACGTAGTAAGCGGAGTCGGCTACTCCATTCTGATTACATGAACATGACACCAAGAAGACCGGGTCCAACCAGGAAACACTATCAGCCTTATGCACCACCCCGGGATTTTGCTGCCTACAGATCAAGGGACCAGCGATTACCACCAGACGCACATAAACCACCTGGAGGTGGATCTTTTAGGACACCTATACAGGAGGAGCAGGCCGATGCCCACAGCACTCTGGCTAAGATTCGTGTCAAGTTTAGTAGGTCCGCCGATGCACCTGCCTACCAGCAGGGACAGAACCAGCTTTACAATGAACTAAACCTAGGAAGGCGGGAAGAGTATGATGTCCTGGATAAAAGGAGAGGACGGGACCCCGAAATGGGTGGCAAACCTCGTAGGAAGAATCCACAGGAGGGCTTGTATAATGAATTGCAGAAGGATAAGATGGCCGAGGCTTACTCTGAGATTGGAATGAAGGGCGAGCGCCGACGTGGGAAAGGTCATGATGGACTGTACCAGGGACTGTCTACAGCCACAAAAGACACCTATGACGCTTTACACATGCAAGCATTGCCACCTAGA"
--            , OligSplitting
--                  [(0,56), (56,112), (112,168), (168,224), (224,280), (280,336), (336,392), (392,448), (448,504), (504,560), (560,616)]
--                  [(28,84), (84,140), (140,196), (196,252), (252,308), (308,364), (364,420), (420,476), (476,532), (532,588), (588,648)])
--     -- ----------
--     ,( "GCACCCGCCGCAGTGAACTCTTCCGCATCCGCCGACAAGCCCTTGTCGAACATGAAGATCCTGACTCTGGGCAAGCTGAGTAGAAACAAGGATGAGGTCAAAGCAATGATTGAGAAGCTGGGAGGGAAGCTCACAGGGACCGCCAACAAAGCCAGTCTCTGCATCAGCACAAAGAAGGAGGTGGAGAAGATGAATAAAAAGATGGAGGAAGTGAAGGAGGCTAACATTCGCGTGGTTTCTGAAGACTTCCTGCAAGATGTGTCCGCAAGTACCAAATCCCTGCAAGAGCTCTTTCTGGCCCATATTTTATCACCCTGGGGAGCCGAGGTTAAGGCCGAACCCGTCGAAGTGGTTGCACCCAGGGGAAAAAGTGGGGCTGCTTTGTCTAAAAAGTCCAAAGGCCAAGTGAAAGAGGAAGGCATCAACAAATCAGAAAAGCGGATGAAGCTC"
--       , OligSplitting
--            [(0,60), (60,120), (120,180), (180,240), (240,300), (300,360), (360,420)]
--            [(30,90), (90,150), (150,210), (210,270), (270,330), (330,390), (390,450)])
--     ,( "GCCCCAGCCGCAGTGAATTCTTCCGCCAGCGCCGACAAGCCACTCTCCAACATGAAGATTCTAACTCTGGGAAAACTGTCTAGGAACAAGGACGAGGTTAAAGCCATGATCGAGAAGCTCGGTGGAAAACTCACCGGGACCGCTAATAAAGCCTCATTGTGTATCTCAACCAAGAAGGAGGTGGAGAAGATGAACAAGAAGATGGAGGAAGTCAAGGAAGCCAACATTCGCGTCGTGTCTGAGGATTTCTTACAAGACGTGTCAGCAAGCACCAAATCGCTTCAGGAGCTCTTCTTAGCCCACATTCTGTCGCCCTGGGGAGCTGAGGTAAAGGCTGAACCTGTAGAAGTCGTGGCCCCTCGTGGTAAAAGCGGAGCTGCACTATCTAAGAAGTCGAAGGGACAGGTAAAGGAGGAGGGCATCAACAAGTCGGAGAAAAGGATGAAGCTG"
--             , OligSplitting
--                  [(0,60), (60,120), (120,180), (180,240), (240,300), (300,360), (360,420)]
--                  [(30,90), (90,150), (150,210), (210,270), (270,330), (330,390), (390,450)])
--     ,( "GCCCCAGCCGCTGTGAACAGCTCAGCTAGTGCAGACAAACCCCTGTCCAACATGAAGATTCTGACACTGGGGAAGCTGTCCCGGAATAAAGACGAAGTGAAGGCCATGATCGAAAAGCTCGGTGGGAAGCTAACTGGAACCGCCAATAAGGCCTCTCTCTGCATCTCCACTAAAAAGGAGGTCGAGAAGATGAACAAGAAGATGGAGGAAGTCAAGGAGGCCAACATTCGCGTCGTCTCCGAAGATTTTCTTCAAGATGTCAGCGCAAGCACTAAGTCCCTGCAAGAGTTGTTCCTGGCTCACATTTTATCTCCTTGGGGCGCCGAAGTCAAAGCAGAGCCAGTGGAAGTGGTTGCGCCTAGAGGAAAGTCCGGTGCTGCCTTGAGCAAGAAGTCCAAGGGGCAGGTAAAGGAAGAGGGTATAAACAAAAGCGAAAAGCGGATGAAATTG"
--            , OligSplitting
--                  [(0,60), (60,120), (120,180), (180,240), (240,300), (300,360), (360,420)]
--                  [(30,90), (90,150), (150,210), (210,270), (270,330), (330,390), (390,450)])
--     -- ----------
--     ,( "ACCAACGTCCCACCGGAAGTAACCGTCTTAACAAACTCGCCGGTAGAGTTACGGGAGCCTAACGTGCTGATCTGTTTCATAGACAAGTTCACACCACCGGTTGTAAACGTAACATGGCTGAGGAATGGGAAACCGGTCACAACAGGGGTATCGGAGACAGTCTTCCTGCCAAGGGAGGATCACCTCTTTAGAAAGTTCCATTACCTGCCGTTTCTGCCCTCGACAGAGGATGTCTACGACTGCCGGGTCGAACATTGGGGATTAGATGAACCGTTATTAAAACACTGGGAATTTGACTCGGGTGGTGGGGATAAGACCCACACC"
--       , OligSplitting
--            [(0,60), (60,120), (120,180), (180,240), (240,300)]
--            [(30,90), (90,150), (150,210), (210,270), (270,324)])
--     ,( "ACCAACGTACCACCAGAGGTCACAGTACTGACAAACTCGCCAGTAGAGTTAAGAGAGCCAAACGTGCTGATATGCTTCATAGACAAGTTCACACCGCCTGTAGTCAACGTTACATGGTTACGGAACGGAAAGCCTGTCACAACCGGAGTCAGTGAAACAGTCTTTTTACCGCGGGAGGACCACCTGTTTCGGAAGTTCCATTACTTACCGTTCCTGCCGAGTACCGAAGATGTCTACGATTGCAGGGTCGAACATTGGGGCCTGGACGAGCCATTACTGAAGCACTGGGAGTTTGATTCGGGAGGAGGGGACAAAACCCATACC"
--             , OligSplitting
--                  [(0,60), (60,120), (120,180), (180,240), (240,300)]
--                  [(30,90), (90,150), (150,210), (210,270), (270,324)])
--     ,( "ACCAACGTCCCACCGGAAGTGACAGTGTTAACCAATTCGCCAGTAGAGTTACGGGAACCCAACGTCCTGATCTGCTTTATCGACAAGTTCACACCACCTGTCGTCAACGTGACTTGGTTAAGAAACGGGAAACCTGTAACAACCGGAGTCTCGGAAACCGTATTCTTACCACGGGAGGACCATTTGTTTAGGAAGTTTCACTACCTGCCGTTTCTCCCGAGCACAGAGGACGTGTATGACTGTAGGGTAGAACACTGGGGATTAGACGAGCCATTACTGAAGCACTGGGAGTTCGACAGTGGCGGAGGAGATAAGACCCACACC"
--            , OligSplitting
--                  [(0,60), (60,120), (120,180), (180,240), (240,300)]
--                  [(30,90), (90,150), (150,210), (210,270), (270,324)])
--     -- ----------
--     ,( "ATTACCTGTCCACCACCGATGTCAGTAGAGCACGCCGACATCTGGGTTAAGTCATACTCCCTATATTCGAGGGAGAGGTACATCTGTAACTCTGGGTTCAAGCGAAAGGCCGGAACATCAAGCCTCACCGAGTGCGTCCTCAACAAGGCTACTAACGTGGCTCACTGGACAACTCCAAGCCTCAAGTGTATTAGAGATCCTGCACTCGTTCATCAACGC"
--       , OligSplitting
--            [(0,49), (49,98), (98,147), (147,196)]
--            [(25,74), (74,123), (123,172), (172,219)])
--     ,( "ATCACTTGCCCTCCTCCAATGTCCGTGGAGCATGCCGACATATGGGTCAAGTCCTACTCACTGTACTCTCGTGAACGCTACATCTGCAACAGTGGCTTTAAACGCAAGGCGGGTACATCTAGTTTGACAGAGTGCGTTCTGAACAAGGCGACCAATGTGGCTCATTGGACAACCCCGAGTCTGAAATGTATACGCGATCCCGCTCTGGTCCATCAAAGA"
--             , OligSplitting
--                  [(0,49), (49,98), (98,147), (147,196)]
--                  [(25,74), (74,123), (123,172), (172,219)])
--     ,( "ATTACATGCCCTCCACCTATGTCCGTGGAACACGCCGATATTTGGGTCAAGTCCTACAGCCTTTACAGCCGGGAGAGGTATATATGCAACAGTGGCTTCAAAAGGAAGGCAGGCACCTCCTCACTTACCGAGTGCGTCCTCAACAAGGCTACTAATGTGGCTCATTGGACTACCCCGTCCTTAAAATGTATCCGAGATCCCGCACTCGTCCATCAGAGA"
--            , OligSplitting
--                  [(0,49), (49,98), (98,147), (147,196)]
--                  [(25,74), (74,123), (123,172), (172,219)])
--     -- ----------
--     ,( "GCAATGGTGACTACCCTTTCAGGACTGTCAGGTGAACAAGGGCCAAGCGGGGATATGACCACGGAGGAGGATTCAGCCACTCACATCAAATTCAGCAAGAGGGATGAAGATGGTAGAGAGCTCGCCGGTGCCACTATGGAACTGAGGGATTGCTCTGGCAAGACAATATCTACCTGGATTTCAGATGGCCATGTGAAGGACTTCTATCTCTACCCAGGTAAGTACACATTCGTAGCAACTGCTGCACCAGACGGATACGAGGTAGCAACTCCCATTACATTCACTGTTAACGAGGATGGAGAGCCAAAGAGTTGCGACAAAACGCATACGTGCCCACAGGTCACAGTGAATGGAGAGGCAACTGAAGGGGACGCACATACAGGGTCAGGCGAAAGT"
--       , OligSplitting
--            [(0,60), (60,120), (120,180), (180,240), (240,300), (300,360)]
--            [(30,90), (90,150), (150,210), (210,270), (270,330), (330,396)])
--     ,( "GCAATGGTAACAACTTTAAGTGGACTCAGTGGGGAGCAGGGTCCATCAGGAGATATGACAACGGAGGAAGATAGTGCCACCCACATTAAGTTCAGCAAACGCGATGAGGACGGGCGGGAGTTAGCAGGGGCAACTATGGAACTGCGGGATTGCTCCGGGAAGACCATATCAACCTGGATAAGCGATGGACACGTGAAGGACTTCTATCTGTATCCAGGGAAATATACTTTTGTCGCCACTGCGGCACCTGATGGATATGAAGTTGCCACACCCATCACTTTCACAGTTAACGAAGATGGCGAGCCAAAAAGTTGTGATAAGACCCATACCTGCCCACAAGTGACGGTGAATGGCGAAGCCACTGAAGGGGATGCACATACAGGTTCGGGTGAGTCC"
--             , OligSplitting
--                  [(0,60), (60,120), (120,180), (180,240), (240,300), (300,360)]
--                  [(30,90), (90,150), (150,210), (210,270), (270,330), (330,396)])
--     ,( "GCAATGGTAACTACTCTGTCTGGCCTGTCTGGAGAGCAAGGCCCATCAGGAGACATGACTACAGAGGAAGACAGCGCCACTCATATCAAATTCTCGAAGAGAGACGAGGACGGAAGAGAGCTGGCCGGAGCTACAATGGAGCTTAGGGATTGCTCAGGAAAGACTATCAGTACCTGGATCTCGGATGGGCATGTGAAGGATTTTTACCTGTATCCCGGCAAATATACTTTCGTTGCCACCGCTGCGCCCGACGGATACGAAGTTGCAACTCCCATAACCTTTACCGTCAATGAAGACGGGGAACCAAAAAGCTGCGATAAAACGCATACCTGTCCTCAGGTAACTGTTAATGGTGAGGCCACTGAGGGAGACGCACATACTGGGTCTGGGGAATCA"
--            , OligSplitting
--                  [(0,60), (60,120), (120,180), (180,240), (240,300), (300,360)]
--                  [(30,90), (90,150), (150,210), (210,270), (270,330), (330,396)])
--     -- ----------
--     ,( "TGGTCACACCCTCAATTTGAGAAAGGATCTGGCGAGTCTGCAATGGTAACAACATTATCGGGTTTGTCTGGGGAACAGGGACCCAGCGGGGACATGACAACAGAAGAAGACTCTGCCACACACATCAAGTTCTCAAAAAGGGACGAGGACGGACGAGAATTAGCCGGAGCTACAATGGAACTGCGCGATTGTTCTGGCAAAACCATTAGCACCTGGATCTCTGATGGCCACGTTAAGGACTTCTACCTCTACCCTGGGAAGTATACCTTTGTAGCAACCGCCGCTCCAGACGGTTATGAAGTTGCGACCCCTATTACTTTCACTGTTAATGAAGACGGACAGGTCACTGTGAACGGCGAAGCGACTGAGGGCGACGCACACACT"
--       , OligSplitting
--            [(0,60), (60,120), (120,180), (180,240), (240,300), (300,360)]
--            [(30,90), (90,150), (150,210), (210,270), (270,330), (330,384)])
--     ,( "TGGAGTCATCCACAATTCGAAAAGGGTTCGGGCGAGTCGGCGATGGTGACTACTCTTTCAGGATTATCCGGTGAACAAGGACCCAGCGGAGATATGACGACCGAAGAAGACTCGGCTACTCACATCAAATTCAGCAAGAGAGATGAGGATGGCAGAGAACTGGCAGGGGCCACTATGGAATTACGAGATTGTAGCGGCAAGACGATCTCTACGTGGATTTCAGATGGGCACGTCAAAGATTTTTACCTGTACCCCGGGAAATATACCTTCGTGGCCACAGCTGCTCCCGACGGATATGAAGTGGCAACACCCATTACATTCACAGTTAACGAGGACGGGCAAGTAACCGTTAACGGGGAGGCAACTGAAGGGGATGCACATACC"
--             , OligSplitting
--                  [(0,60), (60,120), (120,180), (180,240), (240,300), (300,360)]
--                  [(30,90), (90,150), (150,210), (210,270), (270,330), (330,384)])
--     ,( "TGGTCTCATCCACAGTTCGAAAAGGGTAGTGGCGAGTCCGCTATGGTTACAACTCTGTCAGGCTTATCTGGGGAACAAGGGCCAAGTGGAGATATGACAACTGAAGAAGACTCTGCTACCCATATCAAGTTCAGCAAACGCGACGAGGACGGGCGCGAACTGGCTGGCGCAACTATGGAGTTAAGAGACTGCTCTGGAAAGACAATCAGTACATGGATCTCAGACGGCCACGTCAAAGATTTCTACTTATATCCTGGCAAGTACACTTTTGTGGCTACCGCTGCTCCTGATGGCTACGAGGTGGCTACGCCGATCACTTTCACAGTTAACGAAGACGGACAGGTCACGGTAAACGGAGAAGCCACAGAGGGCGATGCTCATACA"
--            , OligSplitting
--                  [(0,60), (60,120), (120,180), (180,240), (240,300), (300,360)]
--                  [(30,90), (90,150), (150,210), (210,270), (270,330), (330,384)])
--    ]