module OligoDesigner.SpecRNAMatrixBuilder (
    matrixBuilderSpec
) where

import Bio.Tools.Sequence.OligoDesigner.Types (MatrixCell(..), Olig(..), OligLight(..), OligSplitting(..), OligSet(..))

import Test.Hspec (Spec, describe, it, shouldBe)
import Bio.Tools.Sequence.OligoDesigner.Utils.RNAMatrixBuilder (rnaMatrix, rebuildMatrix)
import Data.Matrix (matrix)

matrixBuilderSpec :: Spec
matrixBuilderSpec = describe "Oligo-Designer rna matrix builder spec" $ do
    rnaMatrixSpec
    rnaMatrixSimpleSpec

rnaMatrixSpec :: Spec
rnaMatrixSpec =
    describe "rnaMatrixSpec" $
    it "" $ do
        let coords = OligSplitting [(0, 60), (60, 120)] [(30, 90), (90, 150)]
        let oligs =
                OligSet
                    [ Olig "GCTAGCACCAAGGGCCCCAGCGTGTTTCCTCTGGCCCCTAGCAGCAAGAGCACCAGCGGC" 0 60
                    , Olig "GGCACCGCCGCCCTGGGCTGCCTGGTGAAGGACTACTTCCCTGAGCCTGTGACCGTGAGC" 60 120
                    ]
                    [ Olig "CTTCACCAGGCAGCCCAGGGCGGCGGTGCCGCCGCTGGTGCTCTTGCTGCTAGGGGCCAG" 30 90
                    , Olig "CACGCCGCTGGTCAGGGCGCCGCTGTTCCAGCTCACGGTCACAGGCTCAGGGAAGTAGTC" 90 150
                    ]
                    coords
        let res = rnaMatrix oligs
        res `shouldBe` matrix 4 4 generatorRealMatrix
    where
        generatorRealMatrix :: (Int, Int) -> MatrixCell
        generatorRealMatrix (1, 1) = MatrixCell (OligLight "GCTAGCACCAAGGGCCCCAGCGTGTTTCCTCTGGCCCCTAGCAGCAAGAGCACCAGCGGC" (Olig "GCTAGCACCAAGGGCCCCAGCGTGTTTCCTCTGGCCCCTAGCAGCAAGAGCACCAGCGGC" 0 60))
                                                (OligLight "GCTAGCACCAAGGGCCCCAGCGTGTTTCCTCTGGCCCCTAGCAGCAAGAGCACCAGCGGC" (Olig "GCTAGCACCAAGGGCCCCAGCGTGTTTCCTCTGGCCCCTAGCAGCAAGAGCACCAGCGGC" 0 60)) (-36.9)
        generatorRealMatrix (1, 2) = MatrixCell (OligLight "GCTAGCACCAAGGGCCCCAGCGTGTTTCCTCTGGCCCCTAGCAGCAAGAGCACCAGCGGC" (Olig "GCTAGCACCAAGGGCCCCAGCGTGTTTCCTCTGGCCCCTAGCAGCAAGAGCACCAGCGGC" 0 60))
                                                (OligLight "CTTCACCAGGCAGCCCAGGGCGGCGGTGCCGCCGCTGGTGCTCTTGCTGCTAGGGGCCAG" (Olig "CTTCACCAGGCAGCCCAGGGCGGCGGTGCCGCCGCTGGTGCTCTTGCTGCTAGGGGCCAG" 30 90)) (-84.9)
        generatorRealMatrix (1, 3) = MatrixCell (OligLight "GCTAGCACCAAGGGCCCCAGCGTGTTTCCTCTGGCCCCTAGCAGCAAGAGCACCAGCGGC" (Olig "GCTAGCACCAAGGGCCCCAGCGTGTTTCCTCTGGCCCCTAGCAGCAAGAGCACCAGCGGC" 0 60))
                                                (OligLight "GGCACCGCCGCCCTGGGCTGCCTGGTGAAGGACTACTTCCCTGAGCCTGTGACCGTGAGC" (Olig "GGCACCGCCGCCCTGGGCTGCCTGGTGAAGGACTACTTCCCTGAGCCTGTGACCGTGAGC" 60 120)) (-41.8)
        generatorRealMatrix (1, 4) = MatrixCell (OligLight "GCTAGCACCAAGGGCCCCAGCGTGTTTCCTCTGGCCCCTAGCAGCAAGAGCACCAGCGGC" (Olig "GCTAGCACCAAGGGCCCCAGCGTGTTTCCTCTGGCCCCTAGCAGCAAGAGCACCAGCGGC" 0 60))
                                                (OligLight "CACGCCGCTGGTCAGGGCGCCGCTGTTCCAGCTCACGGTCACAGGCTCAGGGAAGTAGTC" (Olig "CACGCCGCTGGTCAGGGCGCCGCTGTTCCAGCTCACGGTCACAGGCTCAGGGAAGTAGTC" 90 150)) (-48.5)
        generatorRealMatrix (2, 2) = MatrixCell (OligLight "CTTCACCAGGCAGCCCAGGGCGGCGGTGCCGCCGCTGGTGCTCTTGCTGCTAGGGGCCAG" (Olig "CTTCACCAGGCAGCCCAGGGCGGCGGTGCCGCCGCTGGTGCTCTTGCTGCTAGGGGCCAG" 30 90))
                                                (OligLight "CTTCACCAGGCAGCCCAGGGCGGCGGTGCCGCCGCTGGTGCTCTTGCTGCTAGGGGCCAG" (Olig "CTTCACCAGGCAGCCCAGGGCGGCGGTGCCGCCGCTGGTGCTCTTGCTGCTAGGGGCCAG" 30 90)) (-68)
        generatorRealMatrix (2, 3) = MatrixCell (OligLight "CTTCACCAGGCAGCCCAGGGCGGCGGTGCCGCCGCTGGTGCTCTTGCTGCTAGGGGCCAG" (Olig "CTTCACCAGGCAGCCCAGGGCGGCGGTGCCGCCGCTGGTGCTCTTGCTGCTAGGGGCCAG" 30 90))
                                                (OligLight "GGCACCGCCGCCCTGGGCTGCCTGGTGAAGGACTACTTCCCTGAGCCTGTGACCGTGAGC" (Olig "GGCACCGCCGCCCTGGGCTGCCTGGTGAAGGACTACTTCCCTGAGCCTGTGACCGTGAGC" 60 120)) (-92.2)
        generatorRealMatrix (2, 4) = MatrixCell (OligLight "CTTCACCAGGCAGCCCAGGGCGGCGGTGCCGCCGCTGGTGCTCTTGCTGCTAGGGGCCAG" (Olig "CTTCACCAGGCAGCCCAGGGCGGCGGTGCCGCCGCTGGTGCTCTTGCTGCTAGGGGCCAG" 30 90))
                                                (OligLight "CACGCCGCTGGTCAGGGCGCCGCTGTTCCAGCTCACGGTCACAGGCTCAGGGAAGTAGTC" (Olig "CACGCCGCTGGTCAGGGCGCCGCTGTTCCAGCTCACGGTCACAGGCTCAGGGAAGTAGTC" 90 150)) (-56.4)
        generatorRealMatrix (3, 3) = MatrixCell (OligLight "GGCACCGCCGCCCTGGGCTGCCTGGTGAAGGACTACTTCCCTGAGCCTGTGACCGTGAGC" (Olig "GGCACCGCCGCCCTGGGCTGCCTGGTGAAGGACTACTTCCCTGAGCCTGTGACCGTGAGC" 60 120))
                                                (OligLight "GGCACCGCCGCCCTGGGCTGCCTGGTGAAGGACTACTTCCCTGAGCCTGTGACCGTGAGC" (Olig "GGCACCGCCGCCCTGGGCTGCCTGGTGAAGGACTACTTCCCTGAGCCTGTGACCGTGAGC" 60 120)) (-45.7)
        generatorRealMatrix (3, 4) = MatrixCell (OligLight "GGCACCGCCGCCCTGGGCTGCCTGGTGAAGGACTACTTCCCTGAGCCTGTGACCGTGAGC" (Olig "GGCACCGCCGCCCTGGGCTGCCTGGTGAAGGACTACTTCCCTGAGCCTGTGACCGTGAGC" 60 120))
                                                (OligLight "CACGCCGCTGGTCAGGGCGCCGCTGTTCCAGCTCACGGTCACAGGCTCAGGGAAGTAGTC" (Olig "CACGCCGCTGGTCAGGGCGCCGCTGTTCCAGCTCACGGTCACAGGCTCAGGGAAGTAGTC" 90 150)) (-81.7)
        generatorRealMatrix (4, 4) = MatrixCell (OligLight "CACGCCGCTGGTCAGGGCGCCGCTGTTCCAGCTCACGGTCACAGGCTCAGGGAAGTAGTC" (Olig "CACGCCGCTGGTCAGGGCGCCGCTGTTCCAGCTCACGGTCACAGGCTCAGGGAAGTAGTC" 90 150))
                                                (OligLight "CACGCCGCTGGTCAGGGCGCCGCTGTTCCAGCTCACGGTCACAGGCTCAGGGAAGTAGTC" (Olig "CACGCCGCTGGTCAGGGCGCCGCTGTTCCAGCTCACGGTCACAGGCTCAGGGAAGTAGTC" 90 150)) (-44.5)
        generatorRealMatrix (x, y) = MatrixCell (OligLight "" (Olig "" 0 0)) (OligLight "" (Olig "" 0 0)) 0
        

rnaMatrixSimpleSpec :: Spec
rnaMatrixSimpleSpec =
    describe "rnaMatrixSimpleSpec" $
    it "" $ do
        let coords = OligSplitting [(0, 6), (6, 12)] [(3, 9), (9, 15)]
        let oligs =
                OligSet
                    [ Olig "AATGGC" 0 6
                    , Olig "GACTGA" 6 12
                    ]
                    [ Olig "CCGCTG" 3 9
                    , Olig "ACTTTC" 9 15
                    ]
                    coords
        let res = rnaMatrix oligs
        res `shouldBe` matrix 4 4 generator
      where
        generator :: (Int, Int) -> MatrixCell
        generator (1, 1) = MatrixCell (OligLight "AATGGC" (Olig "AATGGC" 0 6))
                                      (OligLight "AATGGC" (Olig "AATGGC" 0 6)) 0
        generator (1, 2) = MatrixCell (OligLight "AATGGC" (Olig "AATGGC" 0 6))
                                      (OligLight "CCGCTG" (Olig "CCGCTG" 3 9)) (-2)
        generator (1, 3) = MatrixCell (OligLight "AATGGC" (Olig "AATGGC" 0 6))
                                      (OligLight "GACTGA" (Olig "GACTGA" 6 12)) 0
        generator (1, 4) = MatrixCell (OligLight "AATGGC" (Olig "AATGGC" 0 6))
                                      (OligLight "ACTTTC" (Olig "ACTTTC" 9 15)) 0
        generator (2, 2) = MatrixCell (OligLight "CCGCTG" (Olig "CCGCTG" 3 9))
                                      (OligLight "CCGCTG" (Olig "CCGCTG" 3 9)) (-2.1)
        generator (2, 3) = MatrixCell (OligLight "CCGCTG" (Olig "CCGCTG" 3 9))
                                      (OligLight "GACTGA" (Olig "GACTGA" 6 12)) 0
        generator (2, 4) = MatrixCell (OligLight "CCGCTG" (Olig "CCGCTG" 3 9))
                                      (OligLight "ACTTTC" (Olig "ACTTTC" 9 15)) 0
        generator (3, 3) = MatrixCell (OligLight "GACTGA" (Olig "GACTGA" 6 12))
                                      (OligLight "GACTGA" (Olig "GACTGA" 6 12)) 0
        generator (3, 4) = MatrixCell (OligLight "GACTGA" (Olig "GACTGA" 6 12))
                                      (OligLight "ACTTTC" (Olig "ACTTTC" 9 15)) 0
        generator (4, 4) = MatrixCell (OligLight "ACTTTC" (Olig "ACTTTC" 9 15))
                                      (OligLight "ACTTTC" (Olig "ACTTTC" 9 15)) 0
        generator (x, y) = MatrixCell (OligLight "" (Olig "" 0 0 )) (OligLight "" (Olig "" 0 0)) 0

rebuildMatrixSpec :: Spec
rebuildMatrixSpec =
    describe "rebuildMatrixSpec" $
    it "" $ do
        let coords = OligSplitting [(0, 60), (60, 120)] [(30, 90), (90, 150)]
        let oligs =
                OligSet
                    [ Olig "GCTAGCACCAAGGGCCCCAGCGTGTTTCCTCTGGCCCCTAGCAGCAAGAGCACCAGCGGC" 0 60
                    , Olig "GGCACCGCCGCCCTGGGCTGCCTGGTGAAGGACTACTTCCCTGAGCCTGTGACCGTGAGC" 60 120
                    ]
                    [ Olig "CTTCACCAGGCAGCCCAGGGCGGCGGTGCCGCCGCTGGTGCTCTTGCTGCTAGGGGCCAG" 30 90
                    , Olig "CACGCCGCTGGTCAGGGCGCCGCTGTTCCAGCTCACGGTCACAGGCTCAGGGAAGTAGTC" 90 150
                    ]
                    coords
        let mtx = rnaMatrix oligs
        let newOligs =
                OligSet
                    [ Olig "GCTAGCACCAAGGGCCCCAGCGTGTTTCCTCTGGCCCCTAGCAGCAAGAGCACCAGCGGA" 0 60
                    , Olig "GGCACCGCCGCCCTGGGCTGCCTGGTGAAGGACTACTTCCCTGAGCCTGTGACCGTGAGC" 60 120
                    ]
                    [ Olig "CTTCACCAGGCAGCCCAGGGCGGCGGTTCCGCCGCTGGTGCTCTTGCTGCTAGGGGCCAG" 30 90
                    , Olig "CACGCCGCTGGTCAGGGCGCCGCTGTTCCAGCTCACGGTCACAGGCTCAGGGAAGTAGTC" 90 150
                    ]
                    coords
        let newMtx = rebuildMatrix mtx newOligs
        newMtx `shouldBe` matrix 4 4 generator
  where
    generator :: (Int, Int) -> MatrixCell
    generator (1, 1) = MatrixCell (OligLight "GCTAGCACCAAGGGCCCCAGCGTGTTTCCTCTGGCCCCTAGCAGCAAGAGCACCAGCGGA" (Olig "GCTAGCACCAAGGGCCCCAGCGTGTTTCCTCTGGCCCCTAGCAGCAAGAGCACCAGCGGA" 0 60))
                                  (OligLight "GCTAGCACCAAGGGCCCCAGCGTGTTTCCTCTGGCCCCTAGCAGCAAGAGCACCAGCGGA" (Olig "GCTAGCACCAAGGGCCCCAGCGTGTTTCCTCTGGCCCCTAGCAGCAAGAGCACCAGCGGA" 0 60)) (-40.1)
    generator (1, 2) = MatrixCell (OligLight "GCTAGCACCAAGGGCCCCAGCGTGTTTCCTCTGGCCCCTAGCAGCAAGAGCACCAGCGGA" (Olig "GCTAGCACCAAGGGCCCCAGCGTGTTTCCTCTGGCCCCTAGCAGCAAGAGCACCAGCGGA" 0 60))
                                  (OligLight "CTTCACCAGGCAGCCCAGGGCGGCGGTTCCGCCGCTGGTGCTCTTGCTGCTAGGGGCCAG" (Olig "CTTCACCAGGCAGCCCAGGGCGGCGGTTCCGCCGCTGGTGCTCTTGCTGCTAGGGGCCAG" 30 90)) (-79.3)
    generator (1, 3) = MatrixCell (OligLight "GCTAGCACCAAGGGCCCCAGCGTGTTTCCTCTGGCCCCTAGCAGCAAGAGCACCAGCGGA" (Olig "GCTAGCACCAAGGGCCCCAGCGTGTTTCCTCTGGCCCCTAGCAGCAAGAGCACCAGCGGA" 0 60))
                                  (OligLight "GGCACCGCCGCCCTGGGCTGCCTGGTGAAGGACTACTTCCCTGAGCCTGTGACCGTGAGC" (Olig "GGCACCGCCGCCCTGGGCTGCCTGGTGAAGGACTACTTCCCTGAGCCTGTGACCGTGAGC" 60 120)) (-40.1)
    generator (1, 4) = MatrixCell (OligLight "GCTAGCACCAAGGGCCCCAGCGTGTTTCCTCTGGCCCCTAGCAGCAAGAGCACCAGCGGA" (Olig "GCTAGCACCAAGGGCCCCAGCGTGTTTCCTCTGGCCCCTAGCAGCAAGAGCACCAGCGGA" 0 60))
                                  (OligLight "CACGCCGCTGGTCAGGGCGCCGCTGTTCCAGCTCACGGTCACAGGCTCAGGGAAGTAGTC" (Olig "CACGCCGCTGGTCAGGGCGCCGCTGTTCCAGCTCACGGTCACAGGCTCAGGGAAGTAGTC" 90 150)) (-46.1)
    generator (2, 2) = MatrixCell (OligLight "CTTCACCAGGCAGCCCAGGGCGGCGGTTCCGCCGCTGGTGCTCTTGCTGCTAGGGGCCAG" (Olig "CTTCACCAGGCAGCCCAGGGCGGCGGTTCCGCCGCTGGTGCTCTTGCTGCTAGGGGCCAG" 30 90))
                                  (OligLight "CTTCACCAGGCAGCCCAGGGCGGCGGTTCCGCCGCTGGTGCTCTTGCTGCTAGGGGCCAG" (Olig "CTTCACCAGGCAGCCCAGGGCGGCGGTTCCGCCGCTGGTGCTCTTGCTGCTAGGGGCCAG" 30 90)) (-60.7)
    generator (2, 3) = MatrixCell (OligLight "CTTCACCAGGCAGCCCAGGGCGGCGGTTCCGCCGCTGGTGCTCTTGCTGCTAGGGGCCAG" (Olig "CTTCACCAGGCAGCCCAGGGCGGCGGTTCCGCCGCTGGTGCTCTTGCTGCTAGGGGCCAG" 30 90))
                                  (OligLight "GGCACCGCCGCCCTGGGCTGCCTGGTGAAGGACTACTTCCCTGAGCCTGTGACCGTGAGC" (Olig "GGCACCGCCGCCCTGGGCTGCCTGGTGAAGGACTACTTCCCTGAGCCTGTGACCGTGAGC" 60 120)) (-85.5)
    generator (2, 4) = MatrixCell (OligLight "CTTCACCAGGCAGCCCAGGGCGGCGGTTCCGCCGCTGGTGCTCTTGCTGCTAGGGGCCAG" (Olig "CTTCACCAGGCAGCCCAGGGCGGCGGTTCCGCCGCTGGTGCTCTTGCTGCTAGGGGCCAG" 30 90))
                                  (OligLight "CACGCCGCTGGTCAGGGCGCCGCTGTTCCAGCTCACGGTCACAGGCTCAGGGAAGTAGTC" (Olig "CACGCCGCTGGTCAGGGCGCCGCTGTTCCAGCTCACGGTCACAGGCTCAGGGAAGTAGTC" 90 150)) (-54.0)
    generator (3, 3) = MatrixCell (OligLight "GGCACCGCCGCCCTGGGCTGCCTGGTGAAGGACTACTTCCCTGAGCCTGTGACCGTGAGC" (Olig "GGCACCGCCGCCCTGGGCTGCCTGGTGAAGGACTACTTCCCTGAGCCTGTGACCGTGAGC" 60 120))
                                  (OligLight "GGCACCGCCGCCCTGGGCTGCCTGGTGAAGGACTACTTCCCTGAGCCTGTGACCGTGAGC" (Olig "GGCACCGCCGCCCTGGGCTGCCTGGTGAAGGACTACTTCCCTGAGCCTGTGACCGTGAGC" 60 120)) (-45.7)
    generator (3, 4) = MatrixCell (OligLight "GGCACCGCCGCCCTGGGCTGCCTGGTGAAGGACTACTTCCCTGAGCCTGTGACCGTGAGC" (Olig "GGCACCGCCGCCCTGGGCTGCCTGGTGAAGGACTACTTCCCTGAGCCTGTGACCGTGAGC" 60 120))
                                  (OligLight "CACGCCGCTGGTCAGGGCGCCGCTGTTCCAGCTCACGGTCACAGGCTCAGGGAAGTAGTC" (Olig "CACGCCGCTGGTCAGGGCGCCGCTGTTCCAGCTCACGGTCACAGGCTCAGGGAAGTAGTC" 90 150)) (-81.7)
    generator (4, 4) = MatrixCell (OligLight "CACGCCGCTGGTCAGGGCGCCGCTGTTCCAGCTCACGGTCACAGGCTCAGGGAAGTAGTC" (Olig "CACGCCGCTGGTCAGGGCGCCGCTGTTCCAGCTCACGGTCACAGGCTCAGGGAAGTAGTC" 90 150))
                                  (OligLight "CACGCCGCTGGTCAGGGCGCCGCTGTTCCAGCTCACGGTCACAGGCTCAGGGAAGTAGTC" (Olig "CACGCCGCTGGTCAGGGCGCCGCTGTTCCAGCTCACGGTCACAGGCTCAGGGAAGTAGTC" 90 150)) (-44.5)
    generator (x, y) = MatrixCell (OligLight "" (Olig "" 0 0)) (OligLight "" (Olig "" 0 0)) 0
    